uPortal-Project/uPortal

pom.xml

[UP-4371](https://issues.jasig.org/browse/UP-4371): As [documented](http://mojo.codehaus.org/cobertura-maven-plugin/usage.html), the `<excludes>` Cobertura configuration ought to be wrapped in an `<instrumentation>`.

UP-4371 wrap Cobertura <excludes> in <instrumentation>.

---

build.xml
uportal-war/pom.xml

https://issues.jasig.org/browse/UP-4372
Quiet's maven builds slightly by removing the INFO logs lines from maven output.  Changes build from 157Kb output (https://issues.jasig.org/secure/attachment/14704/build-initial.txt) to around 37Kb output (https://issues.jasig.org/secure/attachment/14705/build-q.txt).
Invoke with -Dmaven.quiet=true; e.g.
ant -Dmaven.quiet=true clean deploy-ear
When there is a compilation error, you'll see something like:
[echo] Running mvn in /home/jwennmacher/projects/uPortal/uportal-war for goals: install -Djasig.ignore -Djasig.ignore
[exec] [ERROR] diagnostic: /home/jwennmacher/projects/uPortal/uportal-war/src/main/java/org/jasig/portal/rest/ImportExportController.java:94: error: ';' expected
[exec]         final PortalDataKey portalDataKey = bob …

UP-4372 Invoke mvn with -q for quieter and slightly faster builds

---

README.md
releaseNotes.html

[UP-4209](https://issues.jasig.org/browse/UP-4209) : Updates `README.md` and release notes documentation to state requirement of Servlet v3 / Tomcat 7 (rather than stating support for Servlet 2.5 which implies Tomcat 6.)
This requirement is only documentation-deep at this point.  This updates the documentation so that the project can confidently not worry about Servlet 2.5 / Tomcat 6 support for uPortal 4.2 and beyond.  Presumably future opportunities will arise to do servlet-spec-y things that benefit from that Servlet 3 version.

UP-4209 require Servlet3 / Tomcat 7+.

---

pom.xml

[UP-4370](https://issues.jasig.org/browse/UP-4370) : widen the exclusion match in the licensing plugin configuration in `pom.xml` to ignore the IntelliJ-generated `overlays` directories when applying license check.
This issue tripped up the uPortal `4.2.0-M1` release process momentarily.

UP-4370 ignore IntelliJ-generated overlays directories on license check.

---

uportal-war/src/main/webapp/WEB-INF/jsp/Search/search.jsp
uportal-war/src/main/webapp/media/skins/respondr/common/common.less
uportal-war/src/main/webapp/media/skins/respondr/common/less/search.less

Added styling the the search results aspect of the Search Portlet. Also added Bootstrap classes to the search form to match the styling found in the rest of uPortal:
New Search Results Styling:
Old Search Results Styling:

UP-4381: Styling improvements to the search results (search portlet)

---

uportal-war/src/main/webapp/media/skins/respondr/common/less/content.less

By changing the portal-titlebar color in Less it would also update the portal-options-links color. This patch makes it so the two variables can work independently.

UP-4380 Updating Less code so that portlet-options-link-color works

---

uportal-war/src/main/resources/layout/theme/respondr/regions.xsl
uportal-war/src/main/resources/layout/theme/respondr/respondr.xsl

https://issues.jasig.org/browse/UP-4407
Adds a new full-width region called mezzanine between customize and the sidebar/pre-content/content areas.  See https://wiki.jasig.org/display/UPC/Respondr+Regions+Feature

UP-4407 Add region mezzanine below customize

---

uportal-war/src/main/java/org/jasig/portal/utils/web/RemoteCookieCheckFilter.java
uportal-war/src/main/resources/properties/contexts/mvcContext.xml

https://issues.jasig.org/browse/UP-4414
Added ignoring configured User-Agent strings to the cookie check process so Universities desiring to have their guest pages indexed so their portal site shows up in Google can do so.
Defaults to allow Google to bypass the cookie check.

UP-4414 Allow Google to index the guest page

---

uportal-war/src/main/webapp/WEB-INF/jsp/Favorites/view.jsp
uportal-war/src/main/webapp/media/skins/respondr/common/less/portlet.less

https://issues.jasig.org/browse/UP-4419
Folded the favorites portlet into a collapsible navbar for easier navigation in mobile view:
Desktop view:
Mobile view (navbar open):

UP-4419: Moved the favorites portlet into a collapsible Bootstrap navbar for mobile view

---

uportal-war/src/main/java/org/jasig/portal/rest/LayoutRESTController.java
uportal-war/src/main/java/org/jasig/portal/rest/PortletsRESTController.java
uportal-war/src/main/java/org/jasig/portal/rest/layout/LayoutPortlet.java

+ Adds 3 new fields to a `LayoutPortlet` object. staticContent, pithyContent, and isAltMaxUrl. We are using static content to display simple content portlets in an Angular display. We are using pithy content to display on a dashboard view. The Alt max URL flag is used to determine some behavior. See [our AngularJS usage](https://github.com/UW-Madison-DoIT/angularjs-portal/blob/master/angularjs-portal-home/src/main/webapp/js/layout/layout-controller.js#L17) for more details.
+ Created new call `/api/portlet/{fname}.json` that returns a `LayoutPortlet` JSON object.
+ Permission on this is based on if the user can render that portlet.

UP-4404 : Add in fetch single portlet

---

uportal-war/src/main/java/org/jasig/portal/url/UrlCanonicalizingFilter.java
uportal-war/src/main/java/org/jasig/portal/utils/web/RemoteCookieCheckFilter.java
uportal-war/src/main/resources/properties/contexts/mvcContext.xml

https://issues.jasig.org/browse/UP-4414
Found that disabling cookies in the browser when user agent is set for Googlebot gets into an infinite HTTP 302 loop.  This change allows for cookies disabled in browser when user-agent is Googlebot or other configured user agent that skips cookie checks to render the guest page, at least with the default data set on my local desktop.  TBD if this actually allows googlebot to work properly.

UP-4414 handle guest access no cookie support in browser

---

uportal-war/src/main/data/default_entities/portlet-definition/search.portlet-definition.xml
uportal-war/src/main/data/default_entities/portlet-definition/searchlauncher.portlet-definition.xml

https://issues.jasig.org/browse/UP-4431
Pre-populating the search auto-suggest with the portlet list gives a much better user experience.  Suggest including in uPortal 4.2.0.

UP-4431 Search auto-suggest defaults to portlet list

---

uportal-war/src/main/java/org/jasig/portal/portlets/lookup/PersonLookupHelperImpl.java

https://issues.jasig.org/browse/UP-4411
When directory search gets results from a person directory search (primarily LDAP in most instances), code used to loop through all returned results and fetch each result from personDir.  If you searched for Thomas you may get several hundred results from LDAP and if you are not an admin user (so permission checks apply), each LDAP result is re-queried from personDir which would go out to LDAP or other external sources to get all the attributes associated with an entity prior to displaying.  Now:
1. limits the amount of re-querying personDir (to get all the attributes that are associated with an entity) to the search result max if displayName is present in all the search results (because the code wanted to display n results of a sorted list).  As …

UP-4411 optimize person dir search

---

uportal-war/src/main/java/org/jasig/portal/portlets/search/SearchPortletController.java
uportal-war/src/main/java/org/jasig/portal/spring/spel/IPortalSpELService.java
uportal-war/src/main/java/org/jasig/portal/spring/spel/PortalSpELServiceImpl.java
uportal-war/src/main/resources/properties/contexts/servicesContext.xml
uportal-war/src/test/resources/org/jasig/portal/rendering/renderingPipelineTestContext.xml

https://issues.jasig.org/browse/UP-4273
Allows search results in the title from portlets to include SpEL expression to replace the search result title with values from the portlet definition.  Primary use case is https://issues.jasig.org/browse/CMSPLT-52 so search results in CMS portlet have a title of the portlet definition, not "cms" as it previously was.  Works with earlier versions of SimpleCMSPortlet but does title substitution with v1.2.0-M3.

UP-4273 Search replaces ${portlet.title} with portlet's title in search results

---

uportal-war/src/main/webapp/WEB-INF/portlet.xml

The background changing portlet broke for mobile devices using Respondr, it was using older muniversality settings.

UP-4439 - Updated mobile background container to point to Respondr

---

bootstrap/utilities/scripts/xmlPagsToEntityPags.groovy
build.xml
utilities/scripts/xmlPagsToEntityPags.groovy

https://issues.jasig.org/browse/UP-4436
Groovy can probably be improved or made more idiomatic.  I'd love to hear feedback on improvements.
Can invoke script 2 ways:
1. using Groovy (requires installing Groovy and having it on path)
groovy bootstrap/utilities/scripts/xmlPagsToEntityPags.groovy uportal-war/src/main/resources/properties/groups/PAGSGroupStoreConfig.xml uportal-war/src/main/data/my_entities/pags-group
Output example at https://issues.jasig.org/secure/attachment/14738/groovyExecutionResults.txt
2. via ant (ugh - not as nice, made script less clear, but done on request)
ant -Dmaven.test.skip=true -Ddir=uportal-war/src/main/data/quickstart_entities/pags-group pagsXmlToEntity
Output similar to groovy execution but wrapped in ant execution.
* As mentioned at end of output example, …

UP-4436 Groovy Script to convert XML PAGS to entity PAGS files

---

assembly/quickstart/README.txt

In response to today's `uportal-user@` email thread, make the included-in-quickstart README clearer about using the operating-system-specific `ant.sh` or `ant.bat`, as appropriate.

Clarify : ant.sh / ant.bat rather than bare ant.

---

uportal-war/src/main/java/org/jasig/portal/layout/dlm/remoting/ChannelListController.java
uportal-war/src/main/java/org/jasig/portal/layout/dlm/remoting/registry/ChannelBean.java
uportal-war/src/main/java/org/jasig/portal/layout/dlm/remoting/registry/ChannelCategoryBean.java
uportal-war/src/main/java/org/jasig/portal/layout/dlm/remoting/registry/v43/PortletCategoryBean.java
uportal-war/src/main/java/org/jasig/portal/layout/dlm/remoting/registry/v43/PortletDefinitionBean.java

https://issues.jasig.org/browse/UP-4503
h3. Sample JSON Output
{
"averageRating": 0,
"description": "View your active Google documents",
"fname": "google-docs",
"id": 59,
"keywords": [
],
"name": "Google Docs",
"parameters": {
"editable": {
"description": "",
"name": "editable",
"value": "false"
}
},
"ratingsCount": 0,
"state": "PUBLISHED",
"title": "Google Docs",
"typeId": 1
}

UP-4503:  Add more info about portlets to the new portletRegistry.json REST API

---

pom.xml
uportal-war/pom.xml
uportal-war/src/main/java/org/jasig/portal/rest/ImportExportController.java

With this you can now do `/api/{entity-type}/{entity-id}?format=JSON` (example `/api/portlet-definition/portal-activity?format=JSON`) which will return a JSON representation of the entity file.  Import may come in the future, but this is a step in that direction. By not passing in a format it will give you XML (just like it is today).

UP-4403 : Adds json export feature

---

uportal-war/src/main/java/org/jasig/portal/spring/security/preauth/PortalPreAuthenticatedProcessingFilter.java
uportal-war/src/test/java/org/jasig/portal/spring/security/preauth/PortalPreAuthenticatedProcessingFilterTest.java

Fire the profile selection event safely, catching, logging, and ignoring exceptions that arise in response to the profile selection event, figuring that failing the entire login is an inappropriate escalation of a failure in honoring the user's expressed desire to use a particular profile.
(Safety added in response to an issue in MyUW where a glitch in the profile selection persistence code broke portal login for affected users, when those users would have been better off being able to log in even if not being able to switch among available profiles.)
See also [portal-dev@ thread](http://thread.gmane.org/gmane.comp.java.jasig.uportal.devel/6221).

UP-4525 : Handle errors around profile selection event publication.

---

uportal-war/src/main/webapp/media/skins/respondr/common/less/header.less
uportal-war/src/main/webapp/media/skins/respondr/common/less/navigation.less

Prevents the menu icon from moving over the uPortal logo on small mobile view.
The menu also works if a larger logo is chosen.
#UP-4475

Menu icon works with larger icons, doesn't collide

---

uportal-war/src/main/webapp/WEB-INF/flows/edit-portlet/portletConfig.jsp

https://issues.jasig.org/browse/UP-4530
Turned autocorrect="off" and autocomplete="off" on the text fields found in the Portlet Manager > Register New Portlet screen:
* Portlet Title  
* Portlet Name  
* Portlet Functional Name  
* Portlet Description

UP-4530: Turned autocorrect off on portlet manager (register new portlet summary info)

---

uportal-war/src/main/java/org/jasig/portal/security/mvc/LoginController.java
uportal-war/src/test/groovy/org/jasig/portal/security/mvc/LoginControllerTest.groovy

URLs, such as //www.google.com/ were making it past the local URL check. Improved check to handle these cases.
https://issues.jasig.org/browse/UP-4559

UP-4559: Improve LoginController at detecting non-local URLs.

---

uportal-war/src/main/java/org/jasig/portal/portlets/jsp/JspInvokerPortletController.java

https://issues.jasig.org/browse/UP-4579
Allows in framework JspInvoker JSP pages to access property values using ${properties.getProperty('propertyName')}

UP-4579 Allow JSPInvoker framwork portlet to access property values

---

uportal-war/pom.xml
uportal-war/src/main/binding/bindings.xjb
uportal-war/src/main/data/quickstart_entities/portlet-definition/about-college-life.portlet-definition.xml
uportal-war/src/main/java/org/jasig/portal/UserInstance.java
uportal-war/src/main/java/org/jasig/portal/io/xml/portlet/PortletDefinitionImporterExporter.java
uportal-war/src/main/java/org/jasig/portal/io/xml/portlet/PortletPortalDataType.java
uportal-war/src/main/java/org/jasig/portal/security/SystemPerson.java
uportal-war/src/main/resources/org/jasig/portal/io/xml/portlet/upgradePortlet_40.xsl
uportal-war/src/main/resources/properties/contexts/importExportContext.xml
uportal-war/src/main/resources/xsd/io/common-io-types-4.0.xsd
uportal-war/src/main/resources/xsd/io/portlet-definition/portlet-definition-4.3.xsd
uportal-war/src/test/groovy/org/jasig/portal/io/xml/portlet/PortletDefinitionImporterExporterTest.groovy
uportal-war/src/test/java/org/jasig/portal/io/xml/BaseXsltDataUpgraderTest.java
uportal-war/src/test/java/org/jasig/portal/io/xml/portlet/PortletDataUpgradeTest.java
uportal-war/src/test/resources/org/jasig/portal/io/xml/portlet/test-portlet-1_40-43_expected.portlet-definition.xml
uportal-war/src/test/resources/org/jasig/portal/io/xml/portlet/test-portlet-1_40.portlet-definitionl.xml

https://issues.jasig.org/browse/UP-4518
Add support for optional lifecycle element.  In a portlet definition, you can add a lifecycle element:
Bumped portlet-definition to 4.3.  Added optional lifecycle element:
```xml
<lifecycle>
<approved>2015-11-06T12:48:19.717-07:00</approved>
<published user="admin">2015-11-06T12:48:19.717-07:00</published>
<expiration user="admin">2015-12-16T12:48:19.717-07:00</expiration>
</lifecycle>
```
* lifecycle with no children: created
* user is optional, defaults to system
* expiration can be in the past (expired) or future (scheduled expiration)
* prior elements not necessary; e.g. can specify just published and approved will be defaulted appropriately

UP-4518 Add Lifecycle to portlet definition, rev portlet definition

---

uportal-war/src/main/java/org/jasig/portal/rendering/PortletDefinitionAttributeSource.java
uportal-war/src/main/resources/properties/contexts/jsonRenderingPipelineContext.xml
uportal-war/src/test/groovy/org/jasig/portal/rendering/PortletDefinitionAttributeSourceTest.groovy

https://issues.jasig.org/browse/UP-4569
Properties added to portlets in layout.json are:
"portletName": "EmergencyAlert"
and either
"webAppName": "/NotificationPortlet"
or
"frameworkPortlet": "true"
Allows the UI to do special handling if need be based on the portlet type.  Typically this information should not be needed by the UI but is available for special circumstances to allow the UI to do special hints or handling.
An example of possible special handling is the app launcher in the favorites; you want the app launcher to activate rather than display in maximized mode, especially if its behavior is to open the portlet in a new window.  This is added in part for the ngPortal support.

UP-4569 Add portlet webapp, name, and framework status to v4.3 layout.JSON

---

uportal-war/src/main/resources/layout/theme/respondr/content.xsl
uportal-war/src/main/resources/layout/theme/respondr/respondr.xsl
uportal-war/src/main/resources/properties/i18n/Messages.properties
uportal-war/src/main/webapp/media/skins/common/javascript/uportal/up-layout-preferences.js
uportal-war/src/main/webapp/media/skins/respondr/common/less/content.less
uportal-war/src/main/webapp/media/skins/respondr/common/less/no-chrome.less

https://issues.jasig.org/browse/UP-4575
When using mobile web view on a mobile device, it is too easy to accidentally move portlets around when attempting to scroll vertically.  Add a drag handle activated on command.  Add a 'Move this portlet' to the options.
When active, display grab handles and 'Cancel portlet move'.
Note: I also took the liberty of re-ordering the menu to a more logical flow, encouraging desired operations (rating, favoriting, adding to layout) on the top of the menu.

UP-4577 Add grab handle for Move Portlet functionality

---

uportal-war/src/main/java/org/jasig/portal/url/UrlSyntaxProviderImpl.java
uportal-war/src/test/java/org/jasig/portal/url/UrlSyntaxProviderImplTest.java

https://issues.jasig.org/browse/UP-4566
If a parameter is not added for a non-targeted or delegate portlet, do not add the &pCa control parameter to the URL

UP-4566 Search adds many parameters to URL, often tripping security alerts

---

uportal-war/src/main/java/org/jasig/portal/groups/pags/dao/jpa/PersonAttributesGroupDefinitionImpl.java
uportal-war/src/main/java/org/jasig/portal/groups/pags/dao/jpa/PersonAttributesGroupTestGroupDefinitionImpl.java
uportal-war/src/main/resources/properties/ehcache.xml

After a lot of research and experimentation, I stumbled across the fix - cache the collection members of the PAGS entities. This creates a cache for each member and then uses the underlying cache (finally) for the entity.

UP-4483: Add caching to member collections of PAGS Group and Test Group

---

uportal-war/src/main/resources/layout/theme/respondr/content.xsl
uportal-war/src/main/resources/layout/theme/respondr/navigation.xsl
uportal-war/src/main/resources/layout/theme/respondr/respondr.xsl
uportal-war/src/main/webapp/media/skins/common/javascript/uportal/up-fragment-permissions-manager.js
uportal-war/src/main/webapp/media/skins/common/javascript/uportal/up-layout-draggable-manager.js
uportal-war/src/main/webapp/media/skins/common/javascript/uportal/up-layout-gallery.js
uportal-war/src/main/webapp/media/skins/common/javascript/uportal/up-layout-preferences.js
uportal-war/src/main/webapp/media/skins/common/javascript/uportal/up-tab-manager.js

https://issues.jasig.org/browse/UP-4549
This update applies to the following restrictions:
- dlm:moveAllowed
- dlm:deleteAllowed
- dlm:editAllowed
- dlm:addChildAllowed
Historically a fragment admin would have to remove these restrictions, make changes, then reinstate them.  That's non-intuitive, so this update allows fragment owners to ignore restrictions when changing fragment layouts.

UP-4549: DLM - Allow Fragment Owners to alter fragments that have DLM restrictions

---

pom.xml
uportal-portlets-overlay/cas/pom.xml

These changes should eliminate all instances of:
* 3.2.1
* 3.2
* 4.0

UP-4643:  Bump commons-collections to 3.2.2 in a few more places

---

uportal-war/src/main/java/org/jasig/portal/rest/SessionRESTController.java

Adds in an originalUsername to the `/uPortal/api/session.json` call in the event you are swapping to another user so that you can do some validation on the client.

UP-4650 Add in originalUsername field

---

uportal-war/src/main/java/org/jasig/portal/layout/profile/ServerProfileMapperImpl.java
uportal-war/src/main/resources/properties/contexts/userContext.xml
uportal-war/src/test/java/org/jasig/portal/layout/profile/ServerProfileMapperImplTest.java

Allows the profile of a user to be dictated by what server the user is coming from, so that the user can test different profiles based on server.
Came up for us when one of our system schools (UW-River Falls) wanted to test our new profile via a specific url (my.uwrf.edu) but still retain the current profile at the old host (my.wisconsin.edu).
Adds the ability to select servers based on regular expression.
This is turned off by default, but does include commented examples of how to use.

UP-4685 Adds ServerProfileMapper

---

uportal-war/src/main/java/org/jasig/portal/layout/UserLayoutHelperImpl.java
uportal-war/src/main/webapp/WEB-INF/flows/reset-user-layout/reset-user-layout.xml

Currently, we have two profiles at Wisconsin.  We have "default" (universality/muniversality) and our new profile "bucky".
When a user clicks reset-my-layout, their "default" resets, but not their "bucky" layout.  So, this adds a method so that if you click that button, all your layouts get reset.  This is off by default, but has a comment on how to turn it on.
I'm guessing this was also a case when we had both respondr and univerality/muniversality.
I'll also mention, that yes, we will be moving away from universality/muniversality soon, so no judging on that.

UP-4691 Adds method to reset user's layouts on all profiles

---

uportal-war/src/main/java/org/jasig/portal/rest/SessionRESTController.java

This patch will add timeout information to the `session.json` API endpoint, so that smarter front-ends, which may not be interacting with the server whilst the user is still active on the page, can decide what the deadline is, and if/how to inform the user.

Update session.json on backend to return timeout data.

---

uportal-war/src/main/webapp/WEB-INF/portlet.xml

…inistration.   I think the second one was a copy-paste error.  This avoids having 2 drop down items in the Add Portlet flow that have the exact same name, but do different things.

[NOJIRA] fix duplicate portlet name

---

uportal-war/src/main/java/org/jasig/portal/rendering/RequestRenderingPipelineUtils.java
uportal-war/src/main/java/org/jasig/portal/rendering/RequestRenderingPipelineUtilsImpl.java
uportal-war/src/main/java/org/jasig/portal/rendering/predicates/GuestUserPredicate.java
uportal-war/src/main/java/org/jasig/portal/rendering/predicates/NotGuestUserPredicate.java
uportal-war/src/main/java/org/jasig/portal/rendering/predicates/RenderOnWebFlagSet.java
uportal-war/src/main/java/org/jasig/portal/rendering/predicates/URLInSpecificState.java

+ `GuestUserPredicate` - Checks if user is the guest user.
+ `NotGuestUserPredicate` - Checks if the user is *NOT* the guest user.
+ `RenderOnWebFlagSet` - Checks if the `renderOnWeb` `portlet-preference` is set to `true`.
+ `URLInSpecificState` - Checks if the URL on the request is in a specific state.

Add in predicates for different setups in the rendering pipeline

---

uportal-war/src/main/java/org/jasig/portal/security/xslt/IXalanMessageHelper.java
uportal-war/src/main/java/org/jasig/portal/security/xslt/XalanMessageHelper.java
uportal-war/src/main/java/org/jasig/portal/security/xslt/XalanMessageHelperBean.java
uportal-war/src/main/resources/layout/theme/respondr/respondr.xsl

When injecting translated messages into javascript (ECM) code from xsl you need to escape special ECM characters as xsl inject unescaped text.
As problem example set messages with simple quote (double simple quote in messages.properties to escape it) and watch on js property (options.messages.movePortletError as example, value generated in respondr.xsl from move.this.portlet.error message property). For this property the gallery isn't working anymore
To solve that, use a java specific function for xsl processors : upMsg:getMessageForEmacsScript, this function use commons.lang3 escaping function from EmacsScript (the library can provide also escaping for Json, HTML, etc...).

NOJIRA: Solve I18N problems on xsl translated messages for javascript properties

---

uportal-war/src/main/resources/layout/theme/respondr/regions.xsl

Solve bug in regions.xsl on region.pre-header introduced by offCanvas commit
The bug was introduced in commit a67cacc on regions.xsl file, see here : https://github.com/Jasig/uPortal/commit/a67cacc695104a41328938680463cf1f9fd26d07
JIRA : https://issues.jasig.org/browse/UP-4725

UP-4725: Region pre-header bug

---

uportal-war/src/main/java/org/apereo/portal/portlet/dao/jpa/JpaPortletDefinitionDao.java

https://issues.jasig.org/browse/UP-4744
With this change, instead of an unusable portal you get...
```
WARN  [http-nio-8080-exec-1-admin] o.a.p.p.d.j.JpaPortletDefinitionDao 2016-10-13 15:37:57,655 - The portletDefinitionId 'admin' is not parsable to a valid portletId (long);  null will be returned
WARN  [http-nio-8080-exec-1-admin] o.a.p.p.r.PortletCategoryRegistryImpl 2016-10-13 15:37:57,675 - Failed to obtain a portletDefinition for groupMember 'EntityIdentifier[type=interface org.apereo.portal.portlet.om.IPortletDefinition,key=admin]';  this circumstance probably means a portlet was deleted in a way that didn't clean up details like categpry memberships and permissions;  all interfaces that delete portlets should go through IPortletPublishingService.removePortletDefinition(); …
```

UP-4744:  Provide better handling for 'bad data' in category memberships

---

uportal-war/src/main/webapp/media/skins/respondr/defaultSkin/less/variables.less

https://issues.jasig.org/browse/UP-4752
Updated Look (links have inherited the darker colors):

UP-4752: Darken muted blue to meet contrast requirements for WCAG AA - rel-4-3-patches

---

uportal-war/src/main/webapp/media/skins/respondr/defaultSkin/less/variables.less

https://issues.jasig.org/browse/UP-4752
Updated Look (links have inherited the darker colors):

UP-4752: Darken muted blue to meet contrast requirements for WCAG AA - master

---

uportal-war/src/main/java/org/apereo/portal/utils/cache/CacheHealthReporterService.java
uportal-war/src/main/java/org/apereo/portal/utils/cache/InsufficientSizeCacheEventListener.java
uportal-war/src/main/resources/properties/contexts/schedulerContext.xml
uportal-war/src/main/resources/properties/ehcache.xml

https://issues.jasig.org/browse/UP-4740
This PR writes warnings to the logs when a cache that should be big enough (for all objects of the corresponding type) starts evicting cache elements due to the configured maxElementsInMemory.
Examples of such caches are those that hold:
- Groups
- Portlets
- Fragments
NOTE:  I'm not sure if a solution like this is a good idea, or if we're better off simply lifting the maxElementsInMemory... allowing the caches to grow to whatever size is needed.

UP-4740:  Report on caches in poor condition

---

pom.xml

Upgrades:
Excludes bugged Commons Collections dependency. Also,
[2.1.2](https://github.com/Jasig/WebproxyPortlet/releases/tag/WebProxyPortlet-2.1.2):
* portlet-preference-driven `BASIC` authentication
* Fix double-encoding of `link` elements
[2.2.0](https://github.com/Jasig/WebproxyPortlet/releases/tag/WebProxyPortlet-2.2.0):
* adds `PreInterceptor` for conveying user attributes as headers on the proxy request.
2.2.1: no-op.
[2.2.2](https://github.com/Jasig/WebproxyPortlet/releases/tag/WebProxyPortlet-2.2.2): 
* Removes overzealous naive caching

Upgrade to Web Proxy Portlet v2.2.2 from v2.1.1.

---

pom.xml

https://issues.jasig.org/browse/WPP-101
Backport fix from `master` to `rel-4-3-patches`.

Upgrade to Web Proxy Portlet v2.2.2 from v2.1.1 - rel-4-3-patches

---

uportal-war/src/main/webapp/WEB-INF/flows/locale-selector/selectLocale.jsp

https://issues.jasig.org/browse/UP-4771
This radio input element does not have a name available to an accessibility API. Valid names are: label element, title attribute.
*Code Snippet*
``` html
<input type="radio" name="locale" value="en_US">
```
...all radio button instances.
label element (either with a "for" attribute or wrapped around the form field), or "title", "aria-label" or "aria-labelledby" attributes as appropriate.
When a form control does not have a name exposed to assistive technologies, users will not be able to identify the purpose of the form control. The name can be provided in multiple ways, including the label element. Other options include use of the title attribute and aria-label which are used to directly provide text that is used for the accessibility name or …

UP-4771: Label radio buttons in User Locales Selector Portlet - master

---

uportal-war/src/main/webapp/WEB-INF/flows/locale-selector/selectLocale.jsp

https://issues.jasig.org/browse/UP-4771
This radio input element does not have a name available to an accessibility API. Valid names are: label element, title attribute.
*Code Snippet*
``` html
<input type="radio" name="locale" value="en_US">
```
...all radio button instances.
label element (either with a "for" attribute or wrapped around the form field), or "title", "aria-label" or "aria-labelledby" attributes as appropriate.
When a form control does not have a name exposed to assistive technologies, users will not be able to identify the purpose of the form control. The name can be provided in multiple ways, including the label element. Other options include use of the title attribute and aria-label which are used to directly provide text that is used for the accessibility name or …

UP-4771: Label radio buttons in User Locales Selector Portlet - rel-4-3-patches

---

uportal-war/src/main/webapp/WEB-INF/jsp/Search/search.jsp

https://issues.jasig.org/browse/UP-4768 …

UP-4768: Add label and type to search portlet input - rel-4-3-patches

---

uportal-war/src/main/webapp/WEB-INF/jsp/Search/search.jsp

https://issues.jasig.org/browse/UP-4768 …

UP-4768: Add label and type to search portlet input - master

---

uportal-war/src/main/webapp/WEB-INF/flows/edit-portlet/portletConfig.jsp
uportal-war/src/main/webapp/WEB-INF/flows/entity-selector/selectEntities.jsp
uportal-war/src/main/webapp/WEB-INF/flows/self-edit-account/editLocalAccount.jsp
uportal-war/src/main/webapp/WEB-INF/tags/edit-portlet/preferenceInput.tag

https://issues.jasig.org/browse/UP-4765 …

UP-4765: register portlet flow labels - master

---

uportal-war/src/main/webapp/WEB-INF/flows/self-edit-account/editLocalAccount.jsp
uportal-war/src/main/webapp/WEB-INF/tags/edit-portlet/preferenceInput.tag

https://issues.jasig.org/browse/UP-4761 …

UP-4761: Label inputs in password manager portlet - master

---

uportal-war/src/main/webapp/WEB-INF/flows/edit-portlet/portletConfig.jsp
uportal-war/src/main/webapp/WEB-INF/flows/entity-selector/selectEntities.jsp
uportal-war/src/main/webapp/WEB-INF/flows/self-edit-account/editLocalAccount.jsp
uportal-war/src/main/webapp/WEB-INF/tags/edit-portlet/preferenceInput.tag

https://issues.jasig.org/browse/UP-4765 …

UP-4765: register portlet flow labels - rel-4-3-patches

---

uportal-war/src/main/webapp/WEB-INF/flows/self-edit-account/editLocalAccount.jsp
uportal-war/src/main/webapp/WEB-INF/tags/edit-portlet/preferenceInput.tag

https://issues.jasig.org/browse/UP-4761 …

UP-4761: Label inputs in password manager portlet - rel-4-3-patches

---

uportal-war/src/main/resources/layout/structure/columns/columns.xsl
uportal-war/src/main/resources/layout/theme/muniversality/components.xsl
uportal-war/src/main/resources/layout/theme/respondr/navigation.xsl
uportal-war/src/main/resources/org/jasig/portal/portlets/SharedParameters.cpd.xml

Change alternativeMaximixedLink to be alternativeMaximizedLink.
This if for 4.3 branch.

UP-4506: Fix alt max link to be spelled correctly - rel-4-3_patches

---

uportal-war/src/main/resources/layout/structure/columns/columns.xsl
uportal-war/src/main/resources/layout/theme/muniversality/components.xsl
uportal-war/src/main/resources/layout/theme/respondr/navigation.xsl
uportal-war/src/main/resources/org/apereo/portal/portlets/SharedParameters.cpd.xml

Change alternativeMaximixedLink to be alternativeMaximizedLink.
This if for master branch.

UP-4506: Fix alt max link to be spelled correctly - master

---

uportal-war/src/main/java/org/apereo/portal/portlets/dynamicskin/FileSystemDynamicSkinService.java

https://issues.jasig.org/browse/UP-4777
Skin generator crashes when there is a missing dynamic variable.
Check if value is empty or missing, skip that variable and warn.

UP-4777: Guard for missing dynamic variable in skin generator - master

---

uportal-war/src/main/java/org/jasig/portal/portlets/dynamicskin/FileSystemDynamicSkinService.java

https://issues.jasig.org/browse/UP-4777
Skin generator crashes when there is a missing dynamic variable.
Check if value is empty or missing, skip that variable and warn.

UP-4777: Guard for missing dynamic variable in skin generator - rel-4-3-patches

---

uportal-war/src/main/webapp/WEB-INF/flows/edit-account/editLocalAccount.jsp
uportal-war/src/main/webapp/WEB-INF/flows/person-lookup/personLookup.jsp
uportal-war/src/main/webapp/WEB-INF/flows/self-edit-account/editLocalAccount.jsp
uportal-war/src/main/webapp/WEB-INF/tags/edit-portlet/preferenceInput.tag

https://issues.jasig.org/browse/UP-4770 …

UP-4770: Label user administration inputs - master

---

uportal-war/src/main/webapp/WEB-INF/flows/edit-account/editLocalAccount.jsp
uportal-war/src/main/webapp/WEB-INF/flows/person-lookup/personLookup.jsp
uportal-war/src/main/webapp/WEB-INF/flows/self-edit-account/editLocalAccount.jsp
uportal-war/src/main/webapp/WEB-INF/tags/edit-portlet/preferenceInput.tag

https://issues.jasig.org/browse/UP-4770 …

UP-4770: Label user administration inputs - rel-4-3-patches

---

uportal-war/src/main/webapp/media/skins/respondr/defaultSkin/less/variables.less

https://issues.jasig.org/browse/UP-4754
Increased contrast between bottom most footer and text

UP-4754: Increase footer contrast to meet WCAG 2 AA standard - master

---

uportal-war/src/main/webapp/media/skins/respondr/defaultSkin/less/variables.less

https://issues.jasig.org/browse/UP-4754
Increased contrast between bottom most footer and text

UP-4754: Increase footer contrast to meet WCAG 2 AA standard - rel-4-3-patches

---

uportal-war/src/main/webapp/WEB-INF/jsp/PopularPortlets/listPortlets.jsp

https://issues.jasig.org/browse/UP-4758
This select element does not have a name available to an accessibility API. Valid names are: label element, title attribute.
``` html
<select id="Pluto_23_ctf6_14_days" name="days"> <option value="1">1</opt...</select>
<select disabled="disabled"><option value="">Title</option></select>
<select disabled="disabled"><option value=""># Times</optio...</select>
```
add `<label>` for `<select>`
two select boxes are generated and under the control of [datatables](https://datatables.net/).
datatable's sDom does not give any straight forward way to add labels for elements.

UP-4758: Label select input in most popular apps portlet - master

---

uportal-war/src/main/webapp/WEB-INF/jsp/PopularPortlets/listPortlets.jsp

https://issues.jasig.org/browse/UP-4758
This select element does not have a name available to an accessibility API. Valid names are: label element, title attribute.
``` html
<select id="Pluto_23_ctf6_14_days" name="days"> <option value="1">1</opt...</select>
<select disabled="disabled"><option value="">Title</option></select>
<select disabled="disabled"><option value=""># Times</optio...</select>
```
add `<label>` for `<select>`
two select boxes are generated and under the control of [datatables](https://datatables.net/).
datatable's sDom does not give any straight forward way to add labels for elements.

UP-4758: Label select input in most popular apps portlet - rel-4-3-patches

---

uportal-war/src/main/webapp/WEB-INF/flows/fragment-audit/fragment-audit.jsp

https://issues.jasig.org/browse/UP-4759
Duplicate id attribute value found on the web page.:
`#Pluto_11_ctf6_14_template`
Code Snippet
``` html
<div id="Pluto_11_ctf6_14_template" class="fl-widget panel panel-default" style="">
```
Add add index as id suffix

UP-4759: Ensure ids are unique in fragment audit portlet - master

---

uportal-war/src/main/webapp/WEB-INF/flows/fragment-audit/fragment-audit.jsp

https://issues.jasig.org/browse/UP-4759
Duplicate id attribute value found on the web page.:
`#Pluto_11_ctf6_14_template`
Code Snippet
``` html
<div id="Pluto_11_ctf6_14_template" class="fl-widget panel panel-default" style="">
```
Add add index as id suffix

UP-4759: Ensure ids are unique in fragment audit portlet - rel-4-3-patches

---

uportal-war/src/main/webapp/WEB-INF/flows/portlet-manager/listChannels.jsp

https://issues.jasig.org/browse/UP-4762
When a form control does not have a name exposed to assistive technologies, users will not be able to identify the purpose of the form control. The name can be provided in multiple ways, including the label element. Other options include use of the title attribute and aria-label which are used to directly provide text that is used for the accessibility name or aria-labelledby which indicates an association with other text on a page that is providing the name. Button controls can have a name assigned in other ways, as indicated below, but in certain situations may require use of label, title, aria-label, or aria-labelledby.
Code Snippet:
``` html
<input type="text" class="portlet-search-input form-control">
```
Add `id`, link label to input with …

UP-4762: Label search box on "Portlet Administration" portlet - master

---

uportal-war/src/main/webapp/WEB-INF/flows/portlet-manager/listChannels.jsp

https://issues.jasig.org/browse/UP-4762
When a form control does not have a name exposed to assistive technologies, users will not be able to identify the purpose of the form control. The name can be provided in multiple ways, including the label element. Other options include use of the title attribute and aria-label which are used to directly provide text that is used for the accessibility name or aria-labelledby which indicates an association with other text on a page that is providing the name. Button controls can have a name assigned in other ways, as indicated below, but in certain situations may require use of label, title, aria-label, or aria-labelledby.
Code Snippet:
``` html
<input type="text" class="portlet-search-input form-control">
```
Add `id`, link label to input with …

UP-4762: Label search box on "Portlet Administration" portlet - rel-4-3-patches

---

uportal-war/src/main/java/org/apereo/portal/IUserIdentityStore.java
uportal-war/src/main/java/org/apereo/portal/RDBMUserIdentityStore.java
uportal-war/src/main/java/org/apereo/portal/layout/dlm/DistributedLayoutManager.java
uportal-war/src/main/java/org/apereo/portal/portlets/googleanalytics/GoogleAnalyticsController.java
uportal-war/src/main/java/org/apereo/portal/security/PersonFactory.java
uportal-war/src/main/java/org/apereo/portal/security/provider/AbstractPersonManager.java
uportal-war/src/main/java/org/apereo/portal/security/provider/ExtendedPersonManager.java
uportal-war/src/main/java/org/apereo/portal/security/provider/IGuestUsernameSelector.java
uportal-war/src/main/java/org/apereo/portal/security/provider/PersonImpl.java
uportal-war/src/main/java/org/apereo/portal/security/provider/RemoteUserPersonManager.java
uportal-war/src/main/java/org/apereo/portal/security/provider/RestrictedPerson.java
uportal-war/src/main/java/org/apereo/portal/security/provider/SimplePersonManager.java
uportal-war/src/main/java/org/apereo/portal/spring/security/evaluator/PortalPermissionEvaluator.java
uportal-war/src/main/resources/properties/contexts/applicationContext.xml
uportal-war/src/main/resources/properties/portal.properties

https://issues.jasig.org/browse/UP-4785
Since the dawn of time uPortal has assigned all unauthenticated users to the same user account:  _guest_.  Not all uPortal deployments support anonymous access, but the vast majority of those that do show *EXACTLY* the same content to every unauthenticated user.
But sometimes that's not what you want.  Sometimes you want to offer a customized guest experience based on the campus, tenancy, language, _etc._ that is used to access the portal (even anonymously).  This task has been difficult, traditionally, due to how aggressively content -- especially guest content -- is cached in the portal.
We should provide the ability to configure multiple guest accounts, and a pluggable, open-ended way to choose a guest account when a user accesses the portal …

UP-4785:  Support for multiple guest users (who may have different content)

---

uportal-war/src/main/webapp/media/skins/respondr/defaultSkin/skin.xml

Upgrades Font Awesome from 4.0.3 to 4.7.0 adding even more awesomeness.
From https://github.com/Jasig/resource-server/pull/46
> https://issues.jasig.org/browse/RESSERV-91
>
> Font Awesome 4.7 adds accessibility icons and additional documentation for making icon usage accessible. (http://fontawesome.io/whats-new/)
> Font Awesome 4.7.x will also likely be the last minor release of the 4.x series.
This would be a candidate for cherry picking to `rel-4-3-patches`. …

NOJIRA: Upgrade from Font Awesome 4.0.3 to 4.7.0

---

uportal-war/src/main/java/org/apereo/portal/rendering/PortletDefinitionAttributeSource.java
uportal-war/src/test/groovy/org/apereo/portal/rendering/PortletDefinitionAttributeSourceTest.groovy

Adds lifecycle to JSON layout feed.  Useful for those not using the rendering pipeline.  For example, AngularJS would like to render a 'Maintenance mode' widget for items in maintenance mode.
Example:
"content": [
{
"_objectType": "portlet",
"url": "/uPortal/api/v4-3/portlet/what-is-uportal.html",
"iconUrl": "/uPortal/media/skins/icons/mobile/feedback.png",
"ID": "u26l1n1110",
"chanID": "53",
"description": "Description of uPortal.",
"fragment": "0",
"precedence": "80.0",
"fname": "what-is-uportal",
"locale": "en_US",
"name": "Welcome to uPortal",
"timeout": "10000",
"title": "Welcome to uPortal",
"typeID": "3",
"deleteAllowed": "false", …

UP-4797 Adds lifecycle to json layout feed

---

docs/README.md
docs/configure-using-jndi.md

*Checklist*
-   [x] the individual contributor license agreement is signed
Captures @bjagg's [findings about using JNDI to override property values](https://groups.google.com/a/apereo.org/d/topic/uportal-user/IM0SnpIlJC0/discussion) to the nascent GitHub-Pages-driven documentation.

Add documentation about configuring using JNDI.

---

.gitignore
docs/GEMFILE
docs/USING_ANGULAR.md
docs/_config.yml

*Checklist*
-   [x] the individual contributor license agreement is signed
(Preview [this change as deployed to apetro's fork](http://apetro.github.io/uPortal/).)
**Adds Jekyll configuration files** supporting running Jekyll to locally build the documentation, using the plugins and assumptions in place in GitHub Pages.
```shell_session
bundle exec jekyll serve
```
**Selects the  GitHub Pages theme named "dinky"**. There are several available such themes to choose among, or uPortal could develop its own theme, or Apereo could develop its own theme, or there's oodles of themes out on The Internet, but as an achievable next step this "dinky" theme looks better than the default minimalist theme.
**Edits Markdown files** to work a little better as …

Theme the GitHub Page website

---

uportal-war/src/main/data/quickstart_entities/portlet-definition/background-preference.portlet-definition.xml
uportal-war/src/main/java/org/apereo/portal/portlets/backgroundpreference/BackgroundSetSelectionStrategy.java
uportal-war/src/main/java/org/apereo/portal/portlets/backgroundpreference/RoleBasedBackgroundSetSelectionStrategy.java
uportal-war/src/main/java/org/apereo/portal/portlets/backgroundpreference/ViewBackgroundPreferenceController.java
uportal-war/src/main/webapp/WEB-INF/jsp/BackgroundPreference/viewBackgroundPreference.jsp

-   [x] the [individual contributor license agreement](https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement) is signed
-   [x] commit message follows [commit guidelines](https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit)
https://issues.jasig.org/browse/UP-4802
Images in the Background Preference portlet currently have no alt text, which isn't ADA compliant. This can be fixed by adding a new portlet-preference containing an alt-text string for each image.

UP-4802: Add alt text attribute to Background Preference portlet thumbnails

---

README.md

[UP-4811](https://issues.jasig.org/browse/UP-4811)
*   Add links to the manuals in the README
*   Add an "about uPortal" section to the README.
*   Add continuous integration status badges at the top of the README.
*   Move command to list ant tasks from header to paragraph.
[WCAG 2.0 …

UP-4811: Add updated links to manuals in the README

---

appveyor.yml

Sample output: https://ci.appveyor.com/project/ChristianMurphy/uportal/build/6
Or see appveyor status in PR status below.
:notebook: Unlike Travis CI, AppVeyor currently runs build matrices serially. Meaning the more configurations there are the longer test completion will take.
[WCAG 2.0 AA]: …

NOJIRA: Configure appveyor for rel-4-3-patches

---

README.md

Arrangment is now:
1. Build statuses
2. About uPortal
3. Help and Support
4. Build Instructions
Continuous integration section has been removed.
Build status and environments is now described by the table at the top of
the page.
Help and support now links to the Manual section to give options for
which version of uPortal manual a person wants to see. …

NOJIRA: Move help and support higher in the README

---

docs/Cas5ClearPass.md
uportal-war/src/main/webapp/WEB-INF/web.xml

Revert change to fix embedded CAS service.
https://issues.jasig.org/browse/UP-4823

UP-4823: Change CAS validate filter from CAS protocol 3 back to 2.

---

.travis.yml
pom.xml

https://issues.jasig.org/browse/UP-4822
Ignore trivial code automatically, update cobertura and coveralls plugins to take advantage of latest features, ensure that `mvn test` is run only once to cut down on CI build time.
> [the] ignoreTrivial switch [...] tells Cobertura to ignore the 
following in the coverage report: Getter methods that simply 
read a class field; Setter methods that set a class field;
Constructors that only set class fields and call a super 
class constructor.
:notebook: These changes would be safe to backport to 4.3 patches
[individual contributor license agreement]: …

UP-4822: Improve Code Test Coverage Metrics

---

pom.xml

https://issues.jasig.org/browse/UP-4822
:notebook: This is the same as #846, PR is being opened to verify that this change will not break CI. :notebook: 
Ignore trivial code automatically, update cobertura and coveralls plugins to take advantage of latest features, ensure that `mvn test` is run only once to cut down on CI build time.
> [the] ignoreTrivial switch [...] tells Cobertura to ignore the 
following in the coverage report: Getter methods that simply 
read a class field; Setter methods that set a class field;
Constructors that only set class fields and call a super 
class constructor.
[individual contributor license agreement]: …

UP-4822: Ignore trivial code from Code Test Coverage

---

build.gradle
checkstyle.xml
pom.xml

Update checkstyle to version 7.6 in both maven and gradle
Adds checkstyle to maven.
Updates checkstyle to version 7.6

UP-4818: Add checkstyle to maven

---

.travis.yml

Each build gradle and maven pull fresh versions of their dependencies down from maven central.
This PR adds configuration that allows Travis CI to cache known dependencies to an S3 bucket that is mounted at the start of each build.
Reducing the network time spent on dependency resolution.
:notebook: Appveyor already is leveraging a similar mechanism, appveyor build with caching takes 5 minutes, Travis CI without caching takes 7 minutes. …

NOJIRA: Cache maven and gradle dependencies to reduce network time on CI

---

uportal-war/src/main/java/org/apereo/portal/portlets/search/PortalSearchResults.java
uportal-war/src/main/java/org/apereo/portal/portlets/search/SearchPortletController.java
uportal-war/src/main/java/org/apereo/portal/portlets/search/google/GoogleCustomSearchService.java
uportal-war/src/main/java/org/apereo/portal/portlets/search/gsa/GsaSearchService.java

Cleans up the search portlet to remove type annotations on operators that can be determined from variable declarations and the operands.

NOJIRA: Remove type annotations in Search that can be implicitly determined

---

build.xml
uportal-war/src/main/java/org/apereo/portal/shell/PortalShell.java

Removed the running the groovy in interactive mode code from up-shell ant target and PortelShell.java
Issue  link - https://issues.jasig.org/browse/UP-4835

UP-4835 - removed the running groovy in interactive mode code 

---

build.xml
uportal-war/src/main/java/org/jasig/portal/shell/PortalShell.java

Removed the running the groovy in interactive mode code from up-shell ant target and PortelShell.java
Issue link - https://issues.jasig.org/browse/UP-4835

Backport UP-4835 Remove Groovy Interactive Shell to rel-4-3-patches

---

README.md
docs/README.md

-   [x] commit message follows [commit guidelines][
Adds overview to homepage of uPortal 5 manual.

NOJIRA: Add status overview to uPortal 5 manual

---

CONTRIBUTING.md

ICLA pdf has been removed, the online submission form is now recommended.

NOJIRA: Update link to individual contributor license agreement

---

pom.xml

Modern uPortal build requires Java 8 or better. Tell Maven this so it can fail faster and more expressively when in a lesser Java environment.
Setting `JAVA_HOME` seems to be in practice pretty difficult. Help a developer out when they haven't yet set it emphatically enough.
-   [ ] commit message follows [commit guidelines][] (Deal with this on squash merge.)

Fail fast when JVM < 8.

---

assembly/quickstart/README.txt
bootstrap/build_includes.xml
releaseNotes.html

Update docs and ant constraint to reflect that uPortal 5 requires Java 8 or above.

NOJIRA: Update ant constraint and documentation to require Java 8

---

uportal-war/src/main/resources/layout/theme/respondr/navigation.xsl
uportal-war/src/main/resources/layout/theme/respondr/regions.xsl
uportal-war/src/main/resources/layout/theme/respondr/respondr.xsl
uportal-war/src/main/webapp/media/skins/respondr/common/less/header.less

https://issues.jasig.org/browse/UP-4850
(Indirectly related to https://issues.jasig.org/browse/UP-2599)
This button will allow easier access to uPortal's content when using screen reading software.
This was a feature way back in 2010 with Universality - this brings the button into Respondr.
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i …

UP-4850: Add "Skip to page content" button in the portal header

---

docs/COMMITTERS.md

Per [up-dev@ vote thread](https://groups.google.com/a/apereo.org/d/topic/uportal-dev/oMLYtLAo3zo/discussion) .
During 72 hour voting period, 4 binding +1s, no vetoes.
+ Christian Murphy: +1
+ Drew Wills: +1
+ Benito Gonzalez: +1
+ Andrew Petro: +1

Add Christian Cousquer (cousquer) as Committer

---

build.gradle
gradle/tasks/clean.gradle
gradle/tasks/hsql.gradle

<https://issues.jasig.org/browse/UP-4859>
Moves custom gradle tasks (@stalele's awesome contibutions) into `gradle/tasks`.
Keeping `build.gradle` focused on configuration, and letting the custom tasks shine on their own. :candle: 
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2C …

UP-4859: Move custom gradle tasks into gradle/tasks folder

---

uPortal-layout/uPortal-layout-core/src/main/java/org/apereo/portal/layout/LayoutPortlet.java
uPortal-marketplace/src/main/java/org/apereo/portal/rest/layout/MarketplaceEntry.java

The marketplace entry feed would almost always return an object with a null url (would return valid url if altmaxurl was set).  This creates a consistent url in the feed.
Doesn't resolve that three constructors are using more or less the same code.
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smi …

Resolves marketplace entry feed almost always having a null url

---

.travis.yml

Removes the Ruby Gem unset step, there are no Ruby steps that would be affected left in the build.

NOJIRA: Remove unset GEM_PATH, project no longer uses Ruby

---

.travis.yml
build.gradle

Build scans offer additional insights into how the build ran ([reference](https://gradle.com/build-scans)).
These scans can be run by adding `--scan` to any call to `./gradlew` or `gradle.bat`.
This automatically creates and tags a buildscan for each build on continuous integration.
[WCAG 2.0 AA]: …

NOJIRA: Generate buildscans on Travis CI

---

.travis.yml
appveyor.yml
build.gradle

https://issues.jasig.org/browse/UP-4854
:notebook: Jacoco can correctly handle Java 8 code, however it will skip subprojects that do not have any tests.
:warning: Coveralls Gradle logs the entire tests results to console. This can causes Travis CI to fail because the log size exceeds 4Mb. Log occurs at `INFO` level, this PR moves logging to quiet to prevent `INFO` and `WARN` level messages from appearing.
[message …

UP-4854: Setup jacoco test coverage and coveralls reporting

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Acknowledges that as a sponsored Apereo project, uPortal is in-scope for Apereo Welcoming Policy, as `CODE_OF_CONDUCT.md`.
Riffing on @ChristianMurphy 's #926 applying @jimhelwig suggestion of by-reference rather than by-value inclusion of Apereo policy.

Acknowledge Apereo Welcoming policy.

---

.travis.yml

Adds OS X 10.12 to the Travis CI build matrix, ensures linux build is running on Ubuntu Trusty.

NOJIRA: Test uPortal on MacOS

---

build.gradle
gradle.properties

<https://issues.jasig.org/browse/UP-4885>
Previously `sourceCompatility` set in `gradle.properties` was creating a dynamic property, which cannot be picked up by the `JavaCompile` task, so the version check was being ignored.
Same goes for `targetCompatibility`, however `targetCompatibility` can be removed since it defaults to `sourceCompatility`.
`gradleVersion` is competing against version set in `.gradle/gradle-wrapper.properties`
:white_check_mark: Example warning output:
```log
* What went wrong:
Execution failed for task ':uPortal-core:compileJava'.
> Could not target platform: 'Java SE 8' using tool chain: 'JDK 7 (1.7)'.
```
[individual contributor license …

UP-4885: Ensure supported Java version is used to compile portal

---

uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/regions.less

https://issues.jasig.org/browse/UP-4896
* Arrow now updates when customize is opened and closed
* Customize drawer no longer partially covers drag and drop areas
Before:
After:

UP-4896: Ensure portlet drag areas are visible and customize arrows work

---

docs/COMMITTERS.md

Reflect [recently concluded vote](https://groups.google.com/a/apereo.org/d/msg/uportal-dev/A5ok2Fiab_M/IQP5g9OvCgAJ) adding @jimhelwig as Committer.

Add Jim Helwig to Committer roster.

---

build.gradle
gradle.properties
uPortal-webapp/build.gradle

Signed, but Apereo hasn't approved it yet.
N/A
N/A
N/A
No view changes.
On a fresh build of uPortal (5), _./gradlew install_ would fail with a message about not being able to find npm.  After changing the uPortal-webapps node to a discrete version, the build succeeded.  I parameterized the nodejs version for the root level, and the the uPortal-webapp level. 
[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agree …

NOJIRA:  Fixed fresh install build issue with nodejs

---

.travis.yml

Travis CI has switched default `dist` to trusty, this allows continued testing with older distribution.
Without pinning errors like https://travis-ci.org/Jasig/uPortal/jobs/257013055 happen.

NOJIRA: Travis CI for release 4.3.x pin linux distribution used for testing

---

uPortal-webapp/src/main/resources/layout/theme/respondr/content.xsl
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/content.less

When the portlet title includes long text, the text goes through the options dropdown, and can extend past the border of the portlet.
The title should be appropriately truncated before "Options" and should show full text on hover.
Before:
After:
[WCAG 2.0 AA]: …

UP-4916: Handle text overflow in portlet title

---

docs/README.md

Relative path to image reset from #982 was off by a level when deployed to GitHub pages. :sweat: 

NOJIRA: Correct relative link to css reset

---

gradle.properties
uPortal-webapp/build.gradle
uPortal-webapp/package-lock.json
uPortal-webapp/package.json
uPortal-webapp/src/main/webapp/media/skins/respondr/common/common.less

https://issues.jasig.org/browse/UP-4924
uPortal 4 contained Bootstrap sources because we directly checked them into the repo.  For uPoirtal 5, we're downloading them and using them in the Gradle build.
That's excellent, but we need to include them (nevertheless) in the uPortal.war package so that uPortal-start can compile skins and so that the dynamic-respondr-skin portlet can function properly. …

UP-4924:  Include Bootstrap sources in the uPortal.war package

---

build.gradle

error prone core 2.1 is throwing
``` log
java.lang.ClassCastException: com.sun.tools.javac.tree.JCTree$JCExpressionStatement cannot be cast to com.sun.source.tree.BlockTree
```
https://travis-ci.org/Jasig/uPortal/jobs/267344574#L1023-L1032
reverting back to previous minor release resolves the issue …

NOJIRA: Pin version of Error Prone core used

---

.travis.yml
appveyor.yml

local `node_modules` folder will still need to be rebuilt each build.
npm can save some time by reusing a copy from its cache folder, rather than downloading from network.
similar to how caching `.gradle` allows CI to preserve its local maven instance between builds.
[WCAG 2.0 AA]: …

ci: preserve global npm cache

---

uPortal-webapp/src/main/resources/properties/contexts/applicationContext.xml

Correct SQL for SQL Server
https://issues.jasig.org/browse/UP-4934

UP-4934: Set size of varbinary for MS SQL Server SQL used by JDBC_PING.

---

uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/regions.less

:link: https://issues.jasig.org/browse/UP-4940
`min-width` for sticky header style switch set to 769px.
The rest of the application switches at 768px, causing sticky header to be out of sync at that specific screen width.
This changes the `min-width` value to 768px and leverages the bootstrap `@screen-sm-min` variable to ensure this stays in sync with the rest of the application.
[message …

UP-4940: Resolve sticky header issues at 798px screen width

---

.editorconfig

> EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.
Supported Editors: http://editorconfig.org/#download
There is some overlap between the `.gitattributes`, linters, and `.editorconfig`.
The main purpose of `.editorconfig` is to remove friction from trying to get an IDE to properly format code, by having the style automatically set …

feat: add cross ide editor configuration file

---

uPortal-soffit/uPortal-soffit-renderer/build.gradle

Since both soffits and core now are both on Spring 4.
Update soffits to leverage the core spring version.

build(gradle): update soffit renderer to use same Spring version as core

---

build.gradle

Every task run will generate a *build/reports/visteg.dot* file.
This file can be converted to svg or png using graphviz `dot -Tsvg visteg.dot -O -v`.
Ref: https://github.com/mmalohlava/gradle-visteg
Example output: [visteg.dot.svg.zip](https://github.com/Jasig/uPortal/files/1377973/visteg.dot.svg.zip)
[WCAG 2.0 AA]: …

build(gradle): add plugin that generates a visualization of task graph

---

.travis.yml

also removes unused `fast_finish` property.
`fast_finish` is only used if there are allowed failures.

ci(travis): add open jdk 8 to the test matrix

---

.travis.yml

add a fix for buffer overflow on precise open jdk 7.
update MacOS test image.

ci(travis): add open jdk 8 to test matrix - rel-4-3-patches backport

---

uPortal-webapp/src/main/webapp/WEB-INF/jsp/BackgroundPreference/viewBackgroundPreference.jsp

This prevents jQuery from overwriting the global $ variable if it exists. Had to move the assignment because the rest of the function was relying on the global var.
https://issues.jasig.org/browse/UP-4675 …

UP-4675:  Added "var" to jQuery assignment

---

uPortal-io/uPortal-io-core/src/main/java/org/apereo/portal/io/xml/IDataUpgrader.java
uPortal-webapp/src/main/resources/layout/theme/respondr/regions.xsl
uPortal-webapp/src/main/resources/layout/theme/respondr/respondr.xsl
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/header.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/regions.less

https://issues.jasig.org/browse/UP-4927
`Eyebrow` is simply a cleaner/clearer/better name than `Pre Header`.  A new major version is the best time to make this change.
Some details about it...
- Layouts exported from uP4 would need to be adjusted (if they include content for the `pre-header` region);  but many/most will not migrate fragment layouts
- Those who are already on the path with uP5 will need to adjust their data
- These changes are few in number (3 items in quickstart)
- This info will be in the "Upgrade Notes" section of the release notes
[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contrib …

UP-4927:  Rename of region 'pre-header' --> 'eyebrow' for uP5

---

uPortal-security/uPortal-security-mvc/src/main/java/org/apereo/portal/security/filter/CorsFilter.java

-   [ x ] the [individual contributor license agreement][] is signed
If a 'POST' request comes in with a null content-type, default it to `CORSRequestType.ACTUAL`

Cors post null content type

---

gradle.properties
uPortal-layout/uPortal-layout-core/src/main/java/org/apereo/portal/layout/UserLayoutHelperImpl.java
uPortal-webapp/src/main/webapp/WEB-INF/flows/reset-user-layout/reset-user-layout.xml

Resolves issue https://issues.jasig.org/browse/UP-4961 by switching the org.jasig class reference to org.apereo.
Also added a change so a local build of uPortal is built as 5.0.1-SNAPSHOT. …

UP-4961:  Changed org.jasig class to org.apereo, and fixed versioning

---

package-lock.json
package.json

Uses [Prettier](https://prettier.io) configured with Google code styles provided by stylelint and eslint to format js, less, and css files.

build: add prettier (js style codemod) to npm build system

---

uPortal-webapp/src/main/webapp/media/skins/respondr/common/javascript/uportal/fluid-jquery-compatibility.js

:memo: corrected `boostrap` -> `bootstrap`

docs: correct reference to bootstrap in docs comment

---

uPortal-webapp/src/main/webapp/WEB-INF/jsp/Search/searchLauncher.jsp

-   [x] [message properties][] have been updated with new phrases (existing property used)
Add an aria-label attribute to webSearchSubmit button.
According to WCAG 2.0 guidelines, buttons must have discernible text that clearly describes the destination, purpose, function, or action for screen reader users.
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resou …

UP-4970: Add aria-label attribute to the web search submit button

---

uPortal-webapp/src/main/resources/org/apereo/portal/io/xml/portlet/upgradePortlet_43.xsl

This change prevents import errors and test failures caused by empty xmlns attributes appearing when a portlet definition is transformed by the data upgrade process.
https://issues.jasig.org/browse/UP-4978
-   [x ] the [individual contributor license agreement][] is signed
-   [x ] commit message follows [commit guidelines][]
In some circumstances when a portlet definition is passed through the automatic upgrade process, the lifecycle element in the resulting portlet definition has an empty xmlns attribute. This can cause:
- a test failure in testUpgradeTestPortlet43to50, as described on the issue tracker for UP-4978; 
- failures on the dataInit task in uPortal-start if local data includes portlet definitions that contain a lifecycle element.
From investigation, it looks as though the …

UP-4978: Apply xmlns attribute globally to stylesheet

---

uPortal-core/src/main/java/org/apereo/portal/security/IPermission.java
uPortal-security/uPortal-security-permissions/src/main/java/org/apereo/portal/security/provider/AuthorizationImpl.java
uPortal-web/src/main/java/org/apereo/portal/portlet/marketplace/MarketplaceService.java
uPortal-webapp/src/main/resources/org/apereo/portal/tenants/sampledata/permission_set/Administrators_BROWSE_APPROVED_portlets-permission-set.xml
uPortal-webapp/src/main/resources/org/apereo/portal/tenants/sampledata/permission_set/Administrators_BROWSE_CREATED_portlets-permission-set.xml
uPortal-webapp/src/main/resources/org/apereo/portal/tenants/sampledata/permission_set/Administrators_BROWSE_EXPIRED_portlets-permission-set.xml
uPortal-webapp/src/main/resources/org/apereo/portal/tenants/sampledata/permission_set/Fragment_Owners_BROWSE_APPROVED_portlets-permission-set.xml
uPortal-webapp/src/main/resources/org/apereo/portal/tenants/sampledata/permission_set/Fragment_Owners_BROWSE_CREATED_portlets-permission-set.xml
uPortal-webapp/src/main/resources/org/apereo/portal/tenants/sampledata/permission_set/Fragment_Owners_BROWSE_EXPIRED_portlets-permission-set.xml

Replicate the portlet SUBSCRIBE permission model for portlet BROWSE permissions so that expired portlets cannot be browsed by non-admin users in the marketplace or searched for using the portal search.
The BROWSE permission which governs access to portlets in search, Customize, and in the Marketplace has been updated to take account of portlet lifecycle state in the same manner as the SUBSCRIBE permission, thereby preventing non-admin users from seeing unpublished portlets. This reflects the normal expectation that setting a portlet to expired means it is no longer visible, overriding other permissions. …

UP-4966 Implement lifecycle state BROWSE permissions

---

uPortal-web/src/main/java/org/apereo/portal/portlet/dao/jpa/JpaPortletDefinitionDao.java

... since fetch.EAGER does an optimal full object graph load of portlet definitions.
https://issues.jasig.org/browse/UP-4942

UP-4942 - fix(jpaPortletDefDao): Remove addFetches() call

---

uPortal-rendering/src/main/java/org/apereo/portal/rendering/predicates/SimplePredicate.java

https://issues.jasig.org/browse/UP-4985
The new Java 8-based Predicate objects are not easy to configure in Spring.  A simple Predicate impl that does Boolean.valueOf on a String would be a big help.

UP-4985:  Add a SimplePredicate class to uPortal-rendering/src/main/java/org/apereo/portal/rendering/predicates that's easy to configure in Spring

---

.travis.yml

Adds ubuntu xenial environment to uPortal test matrix.

ci(travis): include ubuntu xenial in test matrix

---

.travis.yml

:notebook: This is a non-breaking change, aimed at streamlining the testing process for uPortal 5.1+
drop ubuntu trusty (14.04) in favor of Ubuntu xenial (16.04) in continuous integration.
uPortal primarily cares about ensuring current jdks are supported, and we focus on actively supported operating systems.
Trusty LTS will be reaching end of life in April 2019.
JDK 8 was being tested, and JDK 8 continues to be tested on the Xenial build.
uPortal will likely continue to work on Ubuntu Trusty thanks to the abstraction provided by the JDK.
[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license- …

ci(travis): drop trusty for linux ci testing, cross jdk testing remains

---

gradle.properties

> [this is mostly a] bug fix release with a few new features being added. A new `javaversion` condition can be used to detect the version of the JVM running Ant.

chore(deps): update ant to version 1.10.2

---

build.gradle

This plugin hasn't been actively used, but does add time to the ci builds.

refactor: remove build scan recipes plugin for travis

---

uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/grids.less

This ensures that on extra extra small screensizes (<480px) all portlets will display at full screen width.

fix(grid): ensure the flexgrid styles remain consistent on small screens

---

uPortal-portlets/src/main/java/org/apereo/portal/portlets/marketplace/PortletMarketplaceController.java

bug(UP-5006): check initialFilter value is a valid category.

---

docs/fr/GLOSSAIRE.md
docs/fr/README.md
docs/fr/implementer/README.md
docs/fr/implementer/i18n.md

Provide the french translation of the glossary and i18n docs.
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2 …

docs-fr(glossary & i18n) Add i18n and glossary in french doc

---

.travis.yml

Since switching to explicitly run on xenial CI has been unstable.
Hopefully letting Travis pick the preferred dist will stabilize the builds.

ci(travis): let travis ci pick which linux dist to run on

---

README.md
docs/README.md

Adds direct link to view uPortal 5.0 manual, updates link for latest manual to clarify it is uPortal 5.1

docs: add direct links to uPortal 5.0 and 5.1 docs

---

docs/COMMITTERS.md
docs/fr/COMMITTERS.md

uPortal committers [approved this change via up-dev@ vote](https://groups.google.com/a/apereo.org/d/msg/uportal-dev/rkz6aEinw2U/393aldVbAQAJ).
Bumps 3 very inactive committers 
+ Nicholas Blair
+ Jeff Cross
+ James Wennmacher
to committer emeriti status, after a very long foreshadowing of this proposal and Committer vote.
-   [x] documentation is updated, in both English and French …

docs: designate 3 Committers as emeriti

---

uPortal-layout/uPortal-layout-core/src/main/java/org/apereo/portal/layout/LayoutPortlet.java

The `efficencyFlag` _(sic)_ array of booleans in `LayoutPortlet` was adding more complexity than it was increasing efficiency. Drop it.
Simplifies `LayoutPortlet` in advance of expected changes to add feature of exposing portlet publishing parameters.
This pull request is best understood through its succession of commits.
Alas `LayoutPortlet` is not covered by unit tests. This changeset doesn't add any.
-   [ ] commit message follows [commit guidelines][] (they're roughly Conventional Commits)
-   [ ] tests are included (`LayoutPortlet` wasn't covered with unit tests; this changeset doesn't help).
-   [ ] documentation is changed or added (inline code comments added/changed)
-   N/A [message properties][] have been updated …

refactor: trade away modest optimization to reduce LayoutPortlet complexity

---

README.md
docs/README.md
docs/fr/README.md

Modest documentation improvements:
+ Removes language about expecting uPortal 5 release in 2017 (it's released)
+ Hyperlnks `uPortal-start`
+ Clarifies what manual to look at for how to avoid relying upon `uPortal-start`
-   [ ] commit message follows [commit guidelines][] (roughly, conventional commits)
-   N/A tests are included
-   N/A view conforms with [WCAG 2.0 AA][]
[message …

docs: reflect that uPortal 5 released

---

uPortal-utils/uPortal-utils-core/src/test/java/org/apereo/portal/spring/spel/PortalSpELServiceImplTest.java

Addresses:
```
/Users/travis/build/Jasig/uPortal/uPortal-utils/uPortal-utils-core/src/test/java/org/apereo/portal/spring/spel/PortalSpELServiceImplTest.java:56: warning: [UseCorrectAssertInTests] Java assert is used in test. For testing purposes Assert.* matchers should be used.
public void testParser() {
^
(see http://errorprone.info/bugpattern/UseCorrectAssertInTests)
Did you mean 'assertThat("2").isEqualTo(replaced);'?
```
-   [ ] commit message follows [commit guidelines][] (roughly, conventional commits)
-   [x] tests are included (the change is a normalization of a unit test)
-   N/A documentation is changed or added
-   N/A view conforms with [WCAG …

test: JUnit assertTrue not keyword assert in PortalSpELServiceImplTest

---

CONTRIBUTING.md
README.md
docs/README.md
docs/fr/README.md

Per [Google Style for Java](https://google.github.io/styleguide/javaguide.html)
1. "A Java source file is described as being in Google Style if and only if it adheres to the rules"
2. per 4.2, 2 spaces for block indentation.
3. But uPortal (intentionally) uses 4 spaces for block indentation. (cf. `.editorconfig`)
4. Therefore uPortal is not in Google Style
5. So stop characterizing uPortal as in Google Style.
[Apparently](https://github.com/Jasig/uPortal/pull/1182#pullrequestreview-118394752) uPortal uses [Android Open Source Project Java code style](https://source.android.com/setup/contribute/code-style). So characterize as using that instead.
-   N/A tests are included …

docs(badges): characterize code style as "AOSP" rather than "Google"

---

uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/dlm/DistributedLayoutManager.java
uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/dlm/FragmentComparator.java
uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/dlm/LPAAddParameter.java
uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/dlm/LPAChangeAttribute.java
uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/dlm/LPAChangeParameter.java
uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/dlm/LPAEditRestriction.java
uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/dlm/LPARemoveParameter.java
uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/dlm/LPAResetAttribute.java
uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/dlm/LPAResetParameter.java
uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/dlm/MissingPortletDefinition.java
uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/dlm/Precedence.java
uPortal-portlets/src/main/java/org/apereo/portal/portlets/statistics/BasePortletLayoutStatisticsController.java
uPortal-portlets/src/main/java/org/apereo/portal/portlets/statistics/TabRenderStatisticsController.java

The build logs have a bunch of `warning: [MissingOverride]` noise. Add the suggested `@Override` annotations and thereby reduce the noise.
-   [ ] commit message follows [commit guidelines][] (roughly, conventional commits)
-   N/A tests are included (retains existing tests, which still pass, because this is a no-op)
-   [x] documentation is changed or added (documents overridden methods as `@Override`
-   N/A view conforms with [WCAG 2.0 AA][] …

docs: annotate with @Override

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Let's be more radically welcoming of participation and contribution. [HashiCorp's example](https://github.com/hashicorp/packer/commit/87edf671771680e0989798a3460ff00453b9aa89#diff-6a3371457528722a734f3c51d9238c13R3) [inspires](https://twitter.com/ScribblingOn/status/995715231300050944).
-   [ ] commit message follows [commit guidelines][] (roughly follows conventional commits)
-   N/A tests are included
-   N/A view conforms with [WCAG 2.0 AA][] …

docs: lead with radical welcoming of participation

---

docs/developer/other/API.md
uPortal-core/src/main/java/org/apereo/portal/portlet/om/PortletParameterUtility.java
uPortal-core/src/test/java/org/apereo/portal/portlet/om/PortletParameterUtilityTest.java
uPortal-layout/uPortal-layout-core/src/main/java/org/apereo/portal/layout/LayoutPortlet.java

Add portlet publishing parameters as a JavaBean accessor of `LayoutPortlet`, thereby including these parameters in some of the JSON APIs.
Adds `PortletParameterUtilities` with a utility method to convert from `IPortletDefinition`'s `Map<String, IPortletDefinitionParameter>` to the `Map<String, String>` that most simply represents the parameters and yields clean JSON.
After: 
`http://localhost:8080/uPortal/api/portlet/what-is-uportal.json` (note `parameters`):
EDIT: updated from the original description to reflect simpler JSON developed in the course of this PR.
```
{
"portlet": {
"nodeId": "-1",
"title": "Welcome to uPortal",
"description": "Description of uPortal.",
"url": null,
"iconUrl": "/ResourceServingWebapp/rs/tango/0.8.90/32x32/mimetypes/text-html.png",
"faIcon": null,
"fname": …
```

feat(LayoutPortlet): parameters as JavaBean accessor of LayoutPortlet

---

uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/SimpleAttributesMapper.java
uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/SmartLdapGroupStore.java
uPortal-webapp/src/main/resources/properties/contexts/groupsContext.xml

Only few Changes:
- moving SmartLDAPGroupStore bean config into a specific file
- fixing a log debug mistake on properties shown
- CamelCase variable renaming
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties …

Refactoring and cleaning on SmartLDAPGroupStore

---

CODE_OF_CONDUCT.md

The current incubation exit criteria require a conflict resolution policy. Projects like uPortal Home defer to the uPortal code of conduct and with the addition of this conflict resolution policy, they can satisfy that criteria.
-   [ x] the [individual contributor license agreement][] is signed
-   [ x] commit message follows [commit guidelines][]
-   [x ] documentation is changed or added …

docs: adding paragraph on conflict resolution

---

build.gradle

Provide the ability to externalize url setting for local deployement by overriding the default OSS sonatype url.
[WCAG 2.0 AA]: …

UP-5015 - Customize upload artifact url

---

uPortal-webapp/src/main/resources/layout/theme/respondr/regions.xsl
uPortal-webapp/src/main/resources/layout/theme/respondr/respondr.xsl
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/regions.less

changed three files to implement the post-content region for uPortal-5
Drew Willis asked me to make these changes when we found that the post-content region was not usable.
changed uPortal-webapp/src/main/resources/layout/theme/respondr/respondr.xsl to include the call to the region.post-content template found in regions.xsl file
changed uPortal-webapp/src/main/resources/layout/theme/respondr/regions.xsl to include the region.post-content template to put the portlets in the right space with the …

implemented the post-content region

---

build.gradle

scan plugin is now integrated into the gradle platform, plugin is no longer needed.

build: remove unused gradle scan plugin

---

uPortal-webapp/src/main/resources/layout/theme/respondr/respondr.xsl

We have a need to style the portal a little differently when viewing portlets in maximized mode. Building the `<body>`'s `class` attribute was inspired by WordPress [body_class()](https://developer.wordpress.org/reference/functions/body_class/).
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2 …

Using xsl:attribute to build the <body>'s class attribute

---

settings.gradle
uPortal-hibernate/uPortal-hibernate3-dialects/build.gradle
uPortal-hibernate/uPortal-hibernate3-dialects/src/main/java/org/apereo/portal/utils/hibernate3/dialects/MySQL5InnoDBCompressedDialect.java
uPortal-hibernate/uPortal-hibernate3-dialects/src/main/java/org/apereo/portal/utils/hibernate3/dialects/PostgreSQL81Dialect.java
uPortal-hibernate/uPortal-hibernate4-dialects/build.gradle
uPortal-hibernate/uPortal-hibernate4-dialects/src/main/java/org/apereo/portal/utils/hibernate4/dialects/MySQL5InnoDBCompressedDialect.java
uPortal-hibernate/uPortal-hibernate4-dialects/src/main/java/org/apereo/portal/utils/hibernate4/dialects/PostgreSQL81Dialect.java
uPortal-utils/uPortal-utils-core/build.gradle
uPortal-utils/uPortal-utils-core/src/main/java/org/apereo/portal/utils/PortalDialectResolver.java

I moved into 2 submodules the dialects, one module is for portlets having hibernate 3.2 as dependency, and the second is for uPortal and portlets with hibernate 4.x dependency. (the documentation about the use will be documented into uPortal-start).
I needed these two different dependencies because hibernate 3 doesn't manage and import same needs/feature, so i removed a part. (After testing i didn't find any problems).
[individual contributor license agreement]: …

UP-5014 - Moving dialects into specifics submodule to avoid dependency problems

---

docs/implement/layout-management/README.md
docs/implement/layout-management/make-a-fragment.md

Sharing this WIP branch soonest to signal that I'm working on this bit of documentation to de-conflict.
-   [ ] the [individual contributor license agreement][] is signed
[WCAG 2.0 AA]: …

docs(layout): naive copy-and-paste of legacy layout docs content

---

uPortal-content/uPortal-content-portlet/src/main/java/org/apereo/portal/portlet/dao/jpa/PortletPreferenceImpl.java

CLOB column type not supported in all databases. Further, the change causing the issue
was meant to remove the need for CLOB or long text columns.
Fixes #1295.

fix(#1295): remove force column def to CLOB.

---

uPortal-webapp/src/main/resources/org/apereo/portal/groups/smartldap/init.crn

Fix init.crn that doesn't use the property that permit to customize (other than ":") the char to decompose group tree in group id/cn.
[WCAG 2.0 AA]: …

fix(SmartLdapGroupStore): fix configurable property not used

---

uPortal-security/uPortal-security-mvc/src/main/java/org/apereo/portal/security/mvc/LogoutController.java
uPortal-security/uPortal-security-mvc/src/main/java/org/apereo/portal/url/CasLoginRefUrlEncoder.java
uPortal-security/uPortal-security-mvc/src/test/java/org/apereo/portal/url/CasLoginRefUrlEncoderTest.java
uPortal-url/src/main/java/org/apereo/portal/url/IAuthUrlCustomizer.java
uPortal-url/src/main/java/org/apereo/portal/url/UrlAuthCustomizerRegistry.java
uPortal-url/src/main/java/org/apereo/portal/url/UrlCasParamAppenderCustomizer.java
uPortal-url/src/main/java/org/apereo/portal/url/UrlMultiServerNameCustomizer.java
uPortal-utils/uPortal-utils-core/src/main/java/org/apereo/portal/utils/StringToSetUtils.java
uPortal-webapp/src/main/java/org/apereo/portal/context/rendering/RenderingPipelineConfiguration.java
uPortal-webapp/src/main/resources/properties/contexts/jsonRenderingPipelineContext.xml
uPortal-webapp/src/main/resources/properties/contexts/mvcContext.xml
uPortal-webapp/src/main/resources/properties/contexts/securityContext.xml
uPortal-webapp/src/main/resources/properties/security.properties
uPortal-webapp/src/main/webapp/WEB-INF/jsp/Invoker/login.jsp

-   [*] the [individual contributor license agreement][] is signed
-   [*] commit message follows [commit guidelines][]
-   [*] tests are included
Upgrade from the previous Pull Request: https://github.com/Jasig/uPortal/pull/689
This PR is needed when you are deploying a multi-tenant uPortal instance working on several server name. In that case the connexion URL should be adapted to the serverName accessed. As example when the user access to https://servername.edu/uPortal the cas auth url is like https://cas.servername.edu/cas/login?service=https://servername.edu/uPortal/login.
But on an other servername like https://othername.edu/uPortal …

UP-4727 : Managing uPortal running on several servername with CAS

---

uPortal-webapp/src/main/webapp/WEB-INF/web.xml

Fix for issue  #1321. The Character encoding filter has to be applied early in the filter chain to take effect. If another filter touches the request data before it could set the encoding properly, it will just silently do nothing.

Issue #1321: Fix character encoding on form submit

---

uPortal-webapp/src/main/webapp/WEB-INF/jsp/Invoker/sitemap.jsp

Make the sitemap generation script resilient. It will ignore elements in the layout.json that it can't handle.
Fixes #1240

Fix 1240: make sitemap render more resilient

---

gradle.properties
uPortal-webapp/build.gradle
uPortal-webapp/src/main/webapp/media/skins/respondr/common/common_skin.xml

Adds polyfills to uPortal, so that each component does not need to bundle the polyfills individually.
And avoid issues like https://github.com/Jasig/NotificationPortlet/issues/116
Resolves https://github.com/uPortal-contrib/uPortal-web-components/issues/117
[WCAG 2.0 AA]: …

feat: add core js and regenerator runtime polyfills

---

uPortal-webapp/src/main/resources/properties/contexts/flowsContext.xml

Made the `org.apereo.portal.portlets.permissionsadmin` package available for `component-scan` in the flow context, to make the `PermissionAdministrationHelper` available.
fixes #1291

Issue #1291: add permissionsadmin package to component scanning

---

uPortal-webapp/src/main/resources/properties/security.properties

Set the default value of `portal.allServerNames` to `${portal.server}`
Resolves #1372 

fix: Set default value of portal.allServerNames to ${portal.server}

---

uPortal-persondir/src/main/java/org/apereo/portal/RDBMUserIdentityStore.java
uPortal-webapp/src/test/java/org/apereo/portal/io/xml/IdentityImportExportTest.java

This PR fixes a small mistake in JDBC code that affects the ability of the portal to provision new users when they authenticate for the first time.

fix:  correct a mistake in JDBC code when new users are provisioned

---

uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/rest/OidcUserInfoController.java
uPortal-security/uPortal-security-core/src/main/java/org/apereo/portal/security/oauth/IdTokenFactory.java

This PR is a reboot of #1408.
It includes a couple changes:
- It prevents unauthorized (by deployment config) user attributes from appearing in the JWT by use of clever parameters
- It applies the `claims` query string param (the filtering feature) to standard OIDC claims as well as custom claims
In addition to these substantive changes, some items & names were refactored for simplicity. …

Added support for overriding groups and/or custom claims for OIDC tokens

---

docs/fr/implementer/frontend/SKIN_UPORTAL.md
docs/implement/frontend/SKINNING_UPORTAL.md
uPortal-rendering/src/main/java/org/apereo/portal/rendering/xslt/SkinMappingTransformerConfigurationSource.java
uPortal-rendering/src/main/java/org/apereo/portal/rendering/xslt/UserAttributeSkinMappingTransformerConfigurationSource.java
uPortal-rendering/src/main/java/org/apereo/portal/rendering/xslt/UserGroupSkinMappingTransformerConfigurationSource.java
uPortal-webapp/src/main/java/org/apereo/portal/context/rendering/RenderingPipelineConfiguration.java

This permit to apply a default skin based on user attributes or groups. Like it was available before : https://apereo.atlassian.net/wiki/spaces/UPM43/pages/103948823/Set+a+Default+Skin
Also this permit to have an alternative of the bug reported : https://groups.google.com/a/apereo.org/forum/#!topic/uportal-user/JBy0Mp7YvG0 …

feat(skin): apply a default mapping skin

---

uPortal-webapp/src/main/resources/layout/theme/respondr/navigation.xsl

Propose to fix issue #1353
Removed `role="button"`from  https://github.com/Jasig/uPortal/blob/master/uPortal-webapp/src/main/resources/layout/theme/respondr/navigation.xsl#L375
Tested with VoiceOver.
[WCAG 2.0 AA]: …

fix: Accessibility issue

---

renovate.json

Rate limiting is no longer needed now that renovate runs on a regular schedule.
`semanticPrefixChore` is a default setting that didn't need to be set.

chore: renove unused renovate settings

---

uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/rest/oauth/OidcUserInfoController.java
uPortal-webapp/src/main/java/org/apereo/portal/context/rendering/RenderingPipelineConfiguration.java
uPortal-webapp/src/main/resources/layout/theme/respondr/respondr.xsl
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/navigation.less

This enhancement allows portal adopters to specify a property -- `org.apereo.portal.layout.useTabsSize` -- that determines at what display size (and above) the main navigation hamburger menu will switch to tabs.  Before this change, the menu is always hamburger at or below `@screen-sm-max` and always tabs at `@screen-sm-min` or above.
The options (for this property) are:
- sm
- md
- lg
- none
If `none` is specified, the main navigation menu will always be hamburger style.
The property is optional;  the default behavior is the same as before the change.
[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contr …

Allow the main navigation hamburger menu to be used (in lieu of tabs) on any size display -- xs, sm, md, lg, or all of them

---

uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/rest/search/SearchRESTController.java
uPortal-api/uPortal-api-rest/src/test/java/org/apereo/portal/rest/search/SearchRESTControllerTest.java

Resolves #1526.
`/api/v5-0/portal/search` can now take an optional `type` parameter that can be a multi-value parameter.  

#1526 Added the type param to the Search REST API

---

uPortal-webapp/src/main/java/org/apereo/portal/context/rendering/RenderingPipelineConfiguration.java
uPortal-webapp/src/main/resources/layout/theme/respondr/content.xsl
uPortal-webapp/src/main/resources/layout/theme/respondr/regions.xsl
uPortal-webapp/src/main/resources/layout/theme/respondr/respondr.xsl
uPortal-webapp/src/main/resources/properties/i18n/Messages.properties

Resolves #1592 
'Direct URL' option added to the 'Options' menu for a given portlet.
The option will launch a simple modal dialog with the link to the portal.
In the options menu:
Modal dialog:
[WCAG 2.0 AA]: …

Add an option for a 'Direct URL' to the portlet options menu

---

gradle.properties
settings.gradle
uPortal-api/uPortal-api-rest/build.gradle
uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/rest/search/PortletsSearchStrategy.java
uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/rest/search/SearchRESTController.java
uPortal-index/build.gradle
uPortal-index/src/main/java/org/apereo/portal/index/HtmlPortletPreferenceSearchContentExtractor.java
uPortal-index/src/main/java/org/apereo/portal/index/ISearchContentExtractor.java
uPortal-index/src/main/java/org/apereo/portal/index/IndexConfiguration.java
uPortal-index/src/main/java/org/apereo/portal/index/PortalSearchIndexer.java
uPortal-index/src/main/java/org/apereo/portal/index/SearchField.java
uPortal-index/src/test/java/org/apereo/portal/index/HtmlPortletPreferenceSearchContentExtractorTest.java
uPortal-tenants/src/main/java/org/apereo/portal/tenants/TemplateDataTenantOperationsListener.java
uPortal-utils/uPortal-utils-core/src/main/java/org/apereo/portal/xml/XmlUtilities.java
uPortal-webapp/build.gradle
uPortal-webapp/src/main/resources/properties/contexts/schedulerContext.xml

This PR will add search indexing and indexed-based search to uPortal, together with indexing support for some content types (esp. SimpleContentPortlet).
@rodzi @laurenra7 

Add indexed search capabilities to uPortal

---

uPortal-webapp/src/main/resources/layout/theme/respondr/content.xsl

In a recent accessibility test, it was noted that "Options" and "Rate this portlet" can't both be level 2. So this patch moves the options out of the portlet title (`<h2>`) which was accepted by our Accessible Technology group.
[WCAG 2.0 AA]: …

fix: moved portlet options outside the portlet title

---

uPortal-security/uPortal-security-mvc/src/main/java/org/apereo/portal/security/filter/CorsFilter.java
uPortal-webapp/src/main/resources/properties/contexts/securityContext.xml

Recent changes we have made to support to-legged OAuth are breaking CORS support (default config) because `Authorization` is missing from `cors.allowed.headers`.

fix(CORS): add 'Authorization' to the default value(s) for cors.allowed.headers because of our recent changes to support two-legged OAuth

---

uPortal-io/uPortal-io-core/src/main/java/org/apereo/portal/io/xml/XsltDataUpgrader.java
uPortal-utils/uPortal-utils-core/src/main/java/org/apereo/portal/xml/XmlUtilitiesImpl.java
uPortal-webapp/src/test/java/org/apereo/portal/io/xml/BaseXsltDataUpgraderTest.java
uPortal-webapp/src/test/java/org/apereo/portal/io/xml/JaxbPortalDataHandlerServiceTest.java

Recently an intermittent issue with the order in which Spring application context components are bootstrapped has become a very common problem.  When the issue occurs, the application context fails to start.
```
[ant:java] Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.scheduling.support.ScheduledMethodRunnable#3': Cannot resolve reference to bean 'portalSearchIndexer' while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'portalSearchIndexer': Unsatisfied dependency expressed through …
```

fix(startup): fix a race condition with XmlUtilitiesImpl that has become a problem lately

---

uPortal-webapp/src/main/webapp/media/skins/respondr/common/common_skin.xml

Update jQuery and jQuery-migrate to newest 1.x version. This solves an issue we are having that breaks some of our portlets that use jQuery's sub() method.
https://github.com/Jasig/uPortal/issues/1719

GH-1719: Update jQuery and jQuery-migrate to newest 1.x version.

---

.travis.yml

this appears to be the resolution in https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766

ci: use trusty for oracle java 8

---

uPortal-url/src/main/java/org/apereo/portal/url/AbstractUrlBuilder.java
uPortal-url/src/main/java/org/apereo/portal/url/PortletUrlBuilder.java

The portal was failing to render portlet contents due to #1745.  Allowing the parameter maps to be read-write resolved the issue (rolled back https://github.com/Jasig/uPortal/commit/59fe015a9ea32661000543977a8cd424ddba5065 )

#1745 - rolling back the change to make the parameter maps read-only

---

uPortal-utils/uPortal-utils-core/src/main/java/org/apereo/portal/utils/PortalDialectResolver.java

Fix for https://github.com/Jasig/uPortal/issues/1764
-   [X] the [individual contributor license agreement] is signed
There was a typo where a previous bugfix didn't apply to versions of Oracle greater than 12. This resulted in all layout data-imports failing when using Oracle 18c.

fix(oracle): Fix typo that breaks layout imports for Oracle > 12

---

uPortal-webapp/src/main/webapp/WEB-INF/jsp/Invoker/sitemap.jsp

https://github.com/Jasig/uPortal/issues/1766
Unescape the portlet and tab names that display in the sitemap. This prevents portlets from showing up like "Courses &amp; Grades" and shows them correctly as "Courses & Grades".

Unescape portlet and tab names in sitemap.

---

uPortal-webapp/src/main/webapp/WEB-INF/jsp/Invoker/sitemap.jsp

-   [ x ] the [individual contributor license agreement][] is signed
-   [ x ] commit message follows [commit guidelines][]
Use tab's externalId for sitemap links. Fixes GH-1801 and GH-1802.
This fixes 1801 because using the externalId doesn't redirect the user to log in to the portal. This fixes 1802 because the transient tab doesn't have an externalId, so it will never show up in the sitemap at all.

Use tab's externalId for sitemap links. Fixes GH-1801 and GH-1802.

---

uPortal-webapp/src/main/resources/properties/contexts/securityContext.xml
uPortal-webapp/src/main/resources/properties/security.properties

Follow up to #1822 where `encodeServiceUrl` has been made into a property (`cas.ticketValidationFilter.encodeServiceUrl`) that can be set from `uPortal.properties`

feat: made encodeServiceUrl a property that can be set via properties

---

uPortal-webapp/src/main/webapp/WEB-INF/flows/portlet-manager/confirmRemove.jsp

For some deployments the '&' is not escaped for the submit URL. Explicitly setting `escapeXml="false"` to address.
[WCAG 2.0 AA]: …

fix: do not escape submit URL in confirmRemove.jsp

---

uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/gallery.less

Contrast in the customizer drawer needed to be increased. 

fix(wcag-aa): increase contrast in customize drawer

---

uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/SmartLdapGroupStore.java
uPortal-webapp/src/main/resources/org/apereo/portal/groups/smartldap/init.crn

instead of AttributesMapper
UoI needs to use a context mapper over an attribute mapper for greater access to the processing of LDAP records.
[WCAG 2.0 …

feat(smartldap): add support for using ContextMapper

---

uPortal-groups/uPortal-groups-pags/src/main/java/org/apereo/portal/groups/pags/testers/AbstractStringTester.java
uPortal-groups/uPortal-groups-pags/src/main/java/org/apereo/portal/groups/pags/testers/InvertedRegexTester.java
uPortal-groups/uPortal-groups-pags/src/test/java/org/apereo/portal/groups/pags/testers/InvertedRegexTesterTest.java

InvertedRegexTester doesn't provide a logical test result against a multivalued attribute.
The Inverted response should be done against the final result and not for each value test (this case work only on a monovalued attribute). The problem is on the foreach attribute values, when it find a not match it returns true without testing all other values, and so it return always true expect if a single matching result appear. …

fix(pags): InvertedRegexTester against multivalued attributes

---

uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/rest/search/PortletsSearchStrategy.java
uPortal-index/src/main/java/org/apereo/portal/index/PortalSearchIndexer.java
uPortal-webapp/src/main/resources/properties/contexts/schedulerContext.xml

Lucene indexing was not supporting partial term searching without wildcard, which is how search had been working. Also, Lucene indexer needed to run before results were returned (exception broken results).
1. Wildcard is added automatically with this PR
2. Indexer is run at startup
3. Indexer is run every minute by default now
Resolves Issue #2006
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resourc …

fix(search): fix partial searching and run indexer at startup

---

uPortal-webapp/src/main/webapp/WEB-INF/jsp/ImportExportPortlet/import.jsp
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/fluid_stopgap.less

Fix for issue #1878: Added missing fluid uploader css needed to hide button 

fix: correct uploading in admin import/export

---

.github/WORKFLOWS/CI.yml

Travis CI has been getting slower for a while.
More recently they have added more limitation on how many builds free/OSS project can run (https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)
This PR moves the Travis CI build over to GitHub Actions, if successful Travis CI will be dropped in a future PR. …

ci: setup github actions

---

build.gradle

Findbugs is not longer being actively maintained.
Spotbugs is Findbug's successor.
With 400 possible error types it can identify https://spotbugs.github.io
Plus with Spot Security Bugs an additional 130 possible security issues types can be automatically scanned https://find-sec-bugs.github.io/
[WCAG …

test: replace findbugs with spotbugs

---

uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/SimpleAttributesMapper.java
uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/SmartLdapGroupStore.java
uPortal-webapp/src/main/resources/org/apereo/portal/groups/smartldap/init.crn

History in #2141
- Changed the default smartLDAP to use a `attribute-mapper`.  Users wanting a `context-mapper` will need to override the `init.crn`.
- Added some logging to aid in troubleshooting
- Minor changes to make the smartLDAP start up smoother
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies …

#2141 smartLDAP - minor adjustments and remove default context-mapper

---

uPortal-webapp/src/main/resources/layout/theme/respondr/content.xsl

Resolves #2285
Re-added `{up-portlet-title(xxx)}` to content layout used to support dynamic portlet titles.

fix: re-add up-portlet-title token to fix dynamic titles

---

uPortal-webapp/src/main/resources/layout/theme/respondr/navigation.xsl

When tabgroups were active, adding a new tab or maximizing a portlet would create a new "More" tabgroup rather than remain in the current tabgroup. The `tabManager.js` code supports tabgroups. It was looking for an ID that was not migrated to Respondr. This PR adds the needed ID.
[WCAG 2.0 AA]: …

fix: adding a tab or maximizing a portlet now stick to the tabgroup

---

uPortal-url/build.gradle
uPortal-url/src/main/java/org/apereo/portal/url/UrlCasParamAppenderFromPortalRequestCustomizer.java

This new customizer permit to pass params from a portalRequest to the CAS server (usefull when using a WAYF on CAS). All other customizers are doing the job only from CAS URL, this one introduce the possibility from a portal request (usefull when intiated from an IDP).
As example this customizer permit to request the portal from a such request: `https://my.portal.edu/uPortal?idpSelected=IDPid` and the customizer will customize the CAS with service url with a new parameter that permit to preselect …

feat: CAS URL customizing from Portal Request

---

uPortal-webapp/src/main/resources/layout/theme/respondr/regions.xsl

Show the portlet's direct url as read-only text rather than putting it in a form field that shouldn't be edited.
https://github.com/Jasig/uPortal/issues/1858

GH-1858 - Don't show "direct url" in a form input field.

---

uPortal-webapp/src/main/webapp/WEB-INF/jsp/Invoker/sitemap.jsp

Sitemap code in JSP for breaking the columns down had incorrect calculations.
[WCAG 2.0 AA]: …

fix(sitemap): correct sitemap column breaking

---

uPortal-content/uPortal-content-portlet/src/main/java/org/apereo/portal/portlet/dao/jpa/PortletDefinitionImpl.java

Wrong JPA annotation used for localizations inside PortletDefinition

fix: replaced @JoinTable with @CollectionTable for localizations

---

uPortal-webapp/src/main/webapp/WEB-INF/jsp/Search/searchRest.jsp

Can add scripting in via search feature.
To reproduce:
1. Start uPortal
2. visit `http://localhost:8080/uPortal/p/search.ctf2/max/render.uP?pP_query=1234'+alert(5678)+'`

fix: escape search param string

---

uPortal-webapp/src/main/resources/properties/contexts/cacheContext.xml
uPortal-webapp/src/main/resources/properties/ehcache-no-jgroups.xml

1. Add property to dictate which Ehcache configuration file to use (i.e. for dropping JGroups).
2. Add an Ehcache configuration file that does not use JGroups.

fix: make jgroups optional to avoid network delays

---

uPortal-security/uPortal-security-core/src/main/java/org/apereo/portal/security/csrf/PortalCsrfSecurityRequestMatcher.java

uPortal was unable to launch the Swagger / openAPI docs due to a CSRF error. This PR adds the swagger context path / link to the CSRF exception list.

Fix - add swagger endpoint to CSRF ignore list

---

uPortal-web/src/main/java/org/apereo/portal/rendering/DynamicRenderingPipeline.java

History in https://github.com/uPortal-Project/uPortal-start/issues/570
Adds the 'empty' doctype to html pages that does not start with the doctype.
The default XSL processor (Xalan) is still used.

uP 570 - Add workaround for missing doctype

---

uPortal-utils/uPortal-utils-core/src/main/java/org/apereo/portal/events/LoginEvent.java
uPortal-webapp/src/main/resources/properties/portal.properties

An implementer is consuming raw events for analytics. They wish to capture user IP addresses for geolocation. This change adds user IP addresses to Login events.
Tests are not included given the triviality of the change (and some manual testing to confirm correct operation).
There is no documentation around event details. …

feat(events): add ip address to raw login events

---

uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/header.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/regions.less

A deployer reported build failing due to some Less lint issues. This PR represents the corrections to pass the tests.

fix: correct some Less entries

---

uPortal-groups/uPortal-groups-core/src/main/java/org/apereo/portal/groups/RDBMEntityGroupStore.java
uPortal-groups/uPortal-groups-core/src/test/java/org/apereo/portal/groups/RDBMSEntityGroupStoreTest.java

This PR fixes an issue that is causing several Playwright scripts to fail, and causing admin users to not belong to the groups they should.  The issue is that some new caches were recently added, but the objects being stored in the cache were Iterators, which are single use objects.  The fix was to update to instead store the list of groups.
Issue:  https://github.com/uPortal-Project/uPortal/issues/2684
[message …

fix/issue-2684: fix newly added entity group caches

---

uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/rest/PortletsRESTController.java
uPortal-api/uPortal-api-rest/src/test/java/org/apereo/portal/rest/PortletsRESTControllerTest.java

This PR updates the api/portlets.json REST endpoint to optionally allow two new parameters:  
* "requiredPermissionType":  restricts the results to portlets for which the user has the specified permission; if not provided, then defaults to MANAGE
*  "favorite": when true, limits results to those that have been favorited by the user; when false, limits the results to those that have not been favorited …

UPSE-387: Update portlets.json REST endpoint to allow filtering by user's portlet permission and favorite/unfavorite

---

build.gradle

Disable JavaDoc generation to clean up the console output when building.

chore: disable javdoc (for now)

---

uPortal-webapp/src/test/java/org/apereo/portal/events/AnalyticsIncorporationComponentEventSerializationTest.java
uPortal-webapp/src/test/java/org/apereo/portal/events/tincan/json/LrsDataModelSerializeTest.java

This PR aims to fix the following 5 flaky test:
1. [org.apereo.portal.events.tincan.json.LrsDataModelSerializeTest.testLrsActorSerialize](https://github.com/KiruthikaJanakiraman/uPortal/blob/59f8895fe98782e1ff23dd14f9eb2076db09b04e/uPortal-webapp/src/test/java/org/apereo/portal/events/tincan/json/LrsDataModelSerializeTest.java#L49-L57)
2. [org.apereo.portal.events.tincan.json.LrsDataModelSerializeTest.testLrsObjectSerialize](https://github.com/KiruthikaJanakiraman/uPortal/blob/59f8895fe98782e1ff23dd14f9eb2076db09b04e/uPortal-webapp/src/test/java/org/apereo/portal/events/tincan/json/LrsDataModelSerializeTest.java#L60-L80)
3. …

Fix flaky tests: JSON comparison

---

.github/workflows/CI.yml

`v1` is an alias for the latest version in `v1.x.x` it currently points to `v1.1.0` and will point to newer version in the release line when they exist.

chore: use version range in github actions

---

uPortal-webapp/src/test/java/org/apereo/portal/io/xml/IdentityImportExportTestUtilities.java

This PR aims to fix the flaky test: [org.apereo.portal.io.xml.IdentityImportExportTest.testStylesheetDescriptor40ImportExport](https://github.com/uPortal-Project/uPortal/blob/1ff2f1991f4fcae7d629c4faa4efb9315aa19297/uPortal-webapp/src/test/java/org/apereo/portal/io/xml/IdentityImportExportTest.java#L190) similar to previously raised PRs: https://github.com/uPortal-Project/uPortal/pull/2718 and https://github.com/uPortal-Project/uPortal/pull/2719
I found and confirmed the flaky behaviour of the tests using an open-source research tool [NonDex](https://github.com/TestingResearchIllinois/NonDex), which shuffles implementations of nondeterminism operations.
**Problem**
The …

Fix flaky test: testStylesheetDescriptor40ImportExport

---

uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/navigation.less

Prashanti from Texas A&M reported that re-ordering in nav LESS file broken a visual. This PR moves the .active entry lower to address the issue.

fix: move .active CSS back in correct order

---

uPortal-security/uPortal-security-mvc/src/test/java/org/apereo/portal/url/CasLoginRefUrlEncoderTest.java
uPortal-utils/uPortal-utils-url/src/main/java/org/apereo/portal/url/UrlMultiServerNameCustomizer.java

This PR aims to fix an under-determined test: [org.apereo.portal.url.CasLoginRefUrlEncoderTest.testWithParam](https://github.com/KiruthikaJanakiraman/uPortal/blob/23e387d65fd4f740533b1d27d840632724582f43/uPortal-security/uPortal-security-mvc/src/test/java/org/apereo/portal/url/CasLoginRefUrlEncoderTest.java#L62)
I found and confirmed the failure of the test using an open-source research tool [NonDex](https://github.com/TestingResearchIllinois/NonDex), which shuffles implementations of nondeterminism operations.
**Problem**
The test case [org.apereo.portal.url.CasLoginRefUrlEncoderTest.testWithParam](https://github.com/uPortal-Project/uPortal/blob/23e387d65fd4f740533b1d27d …

Fix under-determined test: testWithParam

---

uPortal-core/src/test/java/org/apereo/portal/dao/usertype/FunctionalNameColumnMapperTest.java
uPortal-url/build.gradle
uPortal-url/src/test/java/org/apereo/portal/url/ResourceUrlProviderImplTest.java

-   [X] tests are included
Increased the code test coverage by adding new test cases .

Increasing Test Coverage

---

uPortal-api/uPortal-api-internal/src/test/java/org/apereo/portal/portlets/account/UserAccountHelperTest.java
uPortal-core/src/main/java/org/apereo/portal/EntityIdentifier.java
uPortal-groups/uPortal-groups-local/src/main/java/org/apereo/portal/groups/local/searchers/PersonDirectorySearcher.java
uPortal-security/uPortal-security-permissions/src/main/java/org/apereo/portal/security/provider/AuthorizationImpl.java
uPortal-utils/uPortal-utils-core/src/main/java/org/apereo/portal/PortalInfoProviderImpl.java

-   [X] tests are included
This PR includes minor code refactoring changes - 
**Introduce Explaining Variables:** To make code more readable I have introduced variables.
**Decompose Complex Condition:** Decomposed complex if condition to make it more readable
**Use Constructor Injection:** Instead of using setter injection for usernameAttributeProvider and personAttributeDao, you can use constructor injection. This ensures that the dependencies are injected when the object is created and makes the class immutable.
**Extract Method for Query Transformation:** The switch statement that modifies the query based on the search method can be extracted into a separate method …

Minor code refactoring changes

---

uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/rest/PagsRESTController.java
uPortal-groups/uPortal-groups-pags/src/main/java/org/apereo/portal/groups/pags/dao/EntityPersonAttributesGroupStore.java
uPortal-groups/uPortal-groups-pags/src/main/java/org/apereo/portal/groups/pags/dao/PagsService.java
uPortal-groups/uPortal-groups-pags/src/main/java/org/apereo/portal/groups/pags/dao/jpa/LocalGroupService.java
uPortal-groups/uPortal-groups-pags/src/main/java/org/apereo/portal/groups/pags/dao/jpa/PagsGroupService.java
uPortal-groups/uPortal-groups-pags/src/main/java/org/apereo/portal/groups/pags/dao/jpa/PersonAttributesGroupDefinitionImpl.java
uPortal-layout/uPortal-layout-core/src/main/java/org/apereo/portal/layout/IUserLayoutStore.java
uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/dlm/NodeReferenceFactory.java
uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/dlm/RDBMDistributedLayoutStore.java
uPortal-rendering/src/main/java/org/apereo/portal/url/UrlSyntaxProviderImpl.java
uPortal-url/src/main/java/org/apereo/portal/url/PortalConstants.java
uPortal-web/src/main/java/org/apereo/portal/portlet/rendering/PortletEventCoordinatationService.java
uPortal-web/src/main/java/org/apereo/portal/portlet/rendering/PortletEventCoordinationHelper.java
uPortal-webapp/src/test/java/org/apereo/portal/portlet/rendering/PortletEventCoordinatationServiceTest.java
uPortal-webapp/src/test/java/org/apereo/portal/url/UrlSyntaxProviderImplTest.java

-   [X] tests are included
Refactored the code and worked on the comments-
"// Should refactor this switch to instead choose a service and invoke a method on it" 
" // These 2 should be (public) constants on their respective service classes, not here"
in PagsService.java .

Minor refactoring - Design level refactors

---

uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/TransientUserLayoutManagerWrapper.java

Client reported that security scans have reported that the `pCt` parameter that usually takes the fname of a portlet returns a 200 code if that is set to a file path. While it does not deliver files, the 200 code is an issue. Failure to find an fname is either an consistency issue or someone hacking.
Fix is to throw the exception (rather than swallow it) when the pCt specified portlet is not found.
[commit guidelines]: https://github.com/uPortal-Project/uPortal/blob/master/docs/CONTRIBUT …

fix: throw error on bad pCt parameter (security issue)

---

uPortal-web/src/main/java/org/apereo/portal/portlet/rendering/PortletEventCoordinatationService.java
uPortal-web/src/main/java/org/apereo/portal/portlet/rendering/PortletEventCoordinationHelper.java

Autowired all fields. Added a qualifier for Ehcache. Removed constructor and reference.
A recent refactor broke proper startup of uP. This PR fixes things by adding more Spring `@Autowired` and `@Qualifier` bean management.

Fix for PortletEventCoordinationHelper instantiation

---

uPortal-events/src/main/java/org/apereo/portal/utils/cache/PersonDirectoryCacheKeyGenerator.java

PR 2280 introduced a bug related to attempted caching of the IPersonAttributeDao.getPeopleWithMultivaluedAttributes method. This PR fixes that bug by adding the newly introduced filter to PersonDirectoryCacheKeyGenerator.CachableMethod enum and reference.
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2 …

Added filter to getPeopleWithMultivaluedAttributes caching

---

uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-ga.js

Default GA configuration is not being set. This change adds setting the defaults as global values.
Use of archaic JS compressor prevents use of modern ES6. Will be addressed in uPortal v6, but for now the code was rewritten in an older style that matches the rest of the file.
https://developers.google.com/analytics/devguides/collection/ga4/reference/config#:~:text=Set%20to%20'auto'%20(the,example.com%20for%20the%20domain.
[commit guidelines]: https://github.com/uPortal-Project/uPortal/blob/master/docs/CONTRIBUTING …

fix: added fn configureDefaults() to up-ga.js

---

docs/implement/user-attributes/jdbc.md

This pull request adds configuration for the CachingPersonAttributeDaoImpl bean and myunivCachingPersonDbJdbcAttributeSource bean to the User Attributes documentation in README.md. The new bean merges user attribute sources, enhancing the flexibility and performance of user data retrieval in uPortal.
-> Changes Made
1)Added a CachingPersonAttributeDaoImpl bean  and myunivCachingPersonDbJdbcAttributeSource bean        definition to improve attribute merging.
2)Updated the documentation to guide users on configuring multiple user attribute sources effectively.

Added CachingPersonAttributeDaoImpl bean and myunivCachingPersonDbJdbcAttributeSource bean to the User Attributes docs

---

docs/import_export/README.md

This PR updates the Import/Export tool documentation for uPortal to reflect the new commands in uP5. It replaces outdated commands with the current syntax and usage, ensuring accuracy and clarity. The documentation includes step-by-step instructions and examples to guide users through the Import/Export process. Additionally, it addresses any discrepancies found in the previous version.

Import/Export in the uP5 Manual(#1241)
