uportal-war/src/main/resources/layout/theme/respondr/content.xsl

https://issues.jasig.org/browse/UP-4354
Original: https://issues.jasig.org/secure/attachment/14702/UP-4354.png
Revised:

UP-4354 Respondr hide portlet's options menu if no options

---

uportal-war/src/main/resources/layout/structure/columns/columns.xsl

https://issues.jasig.org/browse/UP-4128
Previous: https://issues.jasig.org/secure/thumbnail/14721/_thumb_14721.png
Now:
Note that this doesn't address existing issue https://issues.jasig.org/browse/UP-4408.  But it at least gives you your navigation tabs back.

UP-4128 Favorites collection presents on its own tab

---

uportal-war/src/main/java/org/jasig/portal/portlet/marketplace/MarketplaceSearchService.java
uportal-war/src/main/java/org/jasig/portal/portlets/search/portletregistry/PortletRegistrySearchService.java

https://issues.jasig.org/browse/UP-4425
See screenshot in issue of problem.  Results now match Portlet Registry search.

UP-4425 Marketplace search returned portlets user doesn't have access to

---

uportal-war/src/main/java/org/jasig/portal/layout/dlm/remoting/UpdatePreferencesServlet.java

Sorry for the white space change. (https://github.com/blog/967-github-secrets to hide them)
+ Adds ability to add a portlet to a tab by fname

UP-4445 : Add in a portlet by fname

---

pom.xml
uportal-war/pom.xml

hoping it might avoid issues with codehaus repo shutting down (and no loss to do it).
https://issues.jasig.org/browse/UP-4455

UP-4455 Upgrade staxmate 

---

uportal-war/src/main/resources/layout/theme/universality/universality.xsl

Modified the footer to always display the current year in the copyright

SSP-3079 Bump copyright to 2015 in footer

---

uportal-war/src/main/webapp/WEB-INF/flows/edit-portlet/portletConfig.jsp

https://issues.jasig.org/browse/UP-4542

UP-4542 Fix for AM/PM not appearing in auto publish/expiration time dropdown

---

uportal-war/src/main/webapp/WEB-INF/flows/edit-portlet/edit-portlet.xml
uportal-war/src/main/webapp/WEB-INF/flows/edit-portlet/portletConfig.jsp
uportal-war/src/main/webapp/media/skins/common/javascript/uportal/entity-selector.js

https://issues.jasig.org/browse/UP-4505
Updated XML parameters for groups and categories to allow 0 selections to be made; updated the logic in entity-selector.js to evaluate if requireSelection = true;

UP-4505: Corrected an issue in entity selector so 0 selections can be made

---

uportal-war/src/main/java/org/jasig/portal/rest/MarketplaceRESTController.java

Creates `/uPortal/api/marketplace/entry/{fname}.json` that returns the entry, if browsable by current user.

UP-4522 : Add in single entry call

---

uportal-war/src/main/java/org/jasig/portal/portlet/marketplace/IMarketplaceService.java
uportal-war/src/main/java/org/jasig/portal/rest/MarketplaceRESTController.java

Last commit to master failed tests. This is a quick fix.

Up 4522 fix add in single entry call

---

uportal-war/src/main/java/org/jasig/portal/layout/dlm/remoting/UpdatePreferencesServlet.java

https://issues.jasig.org/browse/UP-4582

UP-4582: Fix issue with moving portlets into empty columns.

---

uportal-war/src/main/java/org/jasig/portal/layout/dlm/DeleteManager.java
uportal-war/src/main/java/org/jasig/portal/layout/dlm/IntegrationResult.java
uportal-war/src/main/java/org/jasig/portal/layout/dlm/PLFIntegrator.java
uportal-war/src/main/java/org/jasig/portal/layout/dlm/ParameterEditManager.java
uportal-war/src/main/java/org/jasig/portal/layout/dlm/PositionManager.java
uportal-war/src/main/java/org/jasig/portal/layout/dlm/RDBMDistributedLayoutStore.java
uportal-war/src/main/java/org/jasig/portal/layout/dlm/remoting/UpdatePreferencesServlet.java

https://issues.jasig.org/browse/UP-4637

UP-4637:  Fix a DLM bug in PositionManager.isNotReparentable()

---

uportal-war/src/main/resources/properties/ehcache.xml

https://issues.jasig.org/browse/UP-4646

UP-4646:  Add missing tenant-related caches to ehcache.xml

---

uportal-war/src/main/java/org/jasig/portal/portlets/jsp/JspInvokerPortletController.java
uportal-war/src/main/java/org/springframework/context/support/ExtendedPropertySourcesPlaceholderConfigurer.java
uportal-war/src/main/java/org/springframework/context/support/PortalPropertySourcesPlaceholderConfigurer.java
uportal-war/src/main/resources/properties/contexts/applicationContext.xml

https://issues.jasig.org/browse/UP-4647

UP-4647:  Suppress noisy WARN messages for optional properties files

---

pom.xml

Updates commons collections library, while updating portlets that were patched to update the commons collections library.

UP-4643 updates commons collections

---

pom.xml
uportal-portlets-overlay/CalendarPortlet/pom.xml
uportal-portlets-overlay/NewsReaderPortlet/pom.xml
uportal-portlets-overlay/cas/pom.xml

Fixed in Calendar, News Reader, Bookmarks, CAS, Widgets, FunctionalTests, Email, Simple CMS, and Weather

UP-4643:  Provide a fix for bundled webapps suitable for the 4-2 line that is different, in necessary ways, from master

---

uportal-war/src/main/java/org/jasig/portal/rendering/PortalController.java
uportal-war/src/main/java/org/jasig/portal/rendering/UserLayoutStoreComponent.java
uportal-war/src/main/java/org/jasig/portal/services/Authentication.java
uportal-war/src/main/java/org/jasig/portal/spring/security/preauth/PortalPreAuthenticatedProcessingFilter.java

https://issues.jasig.org/browse/UP-4655

UP-4655:  Add some TRACE and DEBUG log entries at key milestones for understanding performance of some key requests

---

uportal-war/src/main/resources/layout/theme/respondr/navigation.xsl
uportal-war/src/main/resources/layout/theme/respondr/respondr.xsl
uportal-war/src/main/webapp/media/skins/respondr/common/less/navigation.less
uportal-war/src/main/webapp/media/skins/respondr/defaultSkin/less/variables.less

This PR corrects (I hope) an issue with the offcanvas menu not appearing on iOS.  The trouble was with the use of 'position:fixed' -- apparently this value works somewhat differently on iOS.
Thanks @cousquer for figuring it out.

UP-4622:  Fix a display issue with the offcanvas menu on iOS

---

build.xml
docs/antHelp.txt

Updated antHelp.txt in docs/
https://issues.jasig.org/browse/UP-4686

UP-4686: Add new option to set Maven thread value for build. 

---

uportal-war/src/main/java/org/jasig/portal/groups/pags/testers/GuestUserTester.java
uportal-war/src/test/java/org/jasig/portal/groups/pags/testers/GuestUserTesterTest.java

see on JIRA for more details : https://issues.jasig.org/browse/UP-4710

UP-4710: Bug on GuestUserTester

---

uportal-war/src/main/resources/layout/theme/respondr/respondr.xsl
uportal-war/src/main/webapp/WEB-INF/jsp/Invoker/tenant-administration.jsp

Make some change on jsp and respondr.xsl to remove hard coded uPortal ContextPath using normalized way.

NOJIRA: fix hard coded uPortal contextPath

---

uportal-war/src/main/java/org/jasig/portal/rest/layout/LayoutPortlet.java

This will mostly benefit [angularjs-portal's widgets mode](http://uw-madison-doit.github.io/angularjs-portal/latest/#/md/expanded), but others could use this as well.
+ Adds some attributes to the `/uPortal/api/layoutDoc` API for widget configuration
+ refactors the efficiency flag check to a generic function.

Add in various portlet preferences for widget configuration to layoutDoc

---

uportal-war/src/main/java/org/jasig/portal/rest/GroupRESTController.java

A simple rest endpoint to get list of groups for the currently authenticated user.
`/uPortal/api/groups`
Related PR: https://github.com/UW-Madison-DoIT/angularjs-portal/pull/503

Adds group rest endpoint

---

uportal-war/src/main/resources/org/jasig/portal/io/export-permission_sets.crn

I tested fix against Postgres and HSQLDB, but not other databases.  I don't expect there would be issues.

UP-4683: Data Import fix for Postgres with string to integer conversion.

---

uportal-war/src/main/java/org/jasig/portal/layout/StylesheetUserPreferencesServiceImpl.java
uportal-war/src/main/java/org/jasig/portal/layout/dlm/RDBMDistributedLayoutStore.java
uportal-war/src/main/java/org/jasig/portal/layout/dlm/UserView.java
uportal-war/src/main/java/org/jasig/portal/utils/FragmentDefinitionUtils.java
uportal-war/src/main/java/org/jasig/portal/utils/IFragmentDefinitionUtils.java
uportal-war/src/test/java/org/jasig/portal/layout/StylesheetUserPreferencesServiceImplTest.java

https://issues.jasig.org/browse/UP-4674
Fixes v4.3 layout.json for layout owners so json includes structure attributes defined in the layout.

UP-4674 add structure attrs in v43 layout json for layout owners

---

.gitignore

Removing from git index eclipse projects path

NOJIRA: Adding eclipse properties to .gitignore

---

uportal-war/src/main/java/org/jasig/portal/portlet/rendering/worker/PortletExecutionWorker.java

https://issues.jasig.org/browse/UP-4689
Fixes issue noticed by CCC which uses Spring Security.  Portlet worker threads can inadvertently delete the Spring SecurityContext.  See issue for details.
This PR furthers uPortal being able to use Spring Security more extensively in the future without impacting the current portal behavior.

UP-4689 Portlet worker threads get same SpringSecurityContext as HTTP thread

---

uportal-war/src/main/java/org/jasig/portal/security/xslt/XalanRestJsonHelper.java
uportal-war/src/main/resources/layout/theme/json/json-v4-3.xsl
uportal-war/src/main/resources/layout/theme/json/json.xsl
uportal-war/src/test/java/org/jasig/portal/rendering/xslt/PipelineStylesheetTest.java
uportal-war/src/test/resources/org/jasig/portal/rendering/renderingPipelineTestContext.xml

UP-3780: Unescaped double quotes in layout.json break uMobile

---

uportal-war/src/main/java/org/jasig/portal/tenants/TemplateDataTenantOperationsListener.java
uportal-war/src/main/resources/properties/contexts/servicesContext.xml
uportal-war/src/test/groovy/org/jasig/portal/tenants/TemplateDataTenantOperationsListenerTest.groovy

https://issues.jasig.org/browse/UP-4717

UP-4717: Add support for relative tenant datafiles on update.

---

build.properties.sample
build.xml

Adding the possibility to set the var env from build.properties

NOJIRA: Possibility setting env from build.properties

---

uportal-war/src/main/resources/properties/ehcache.xml

https://issues.jasig.org/browse/UP-4738
These are proposed changes to default cache sizes.  Please be liberal with your comments and help us choose good defaults.

UP-4738:  Re-tune caches settings for Groups+Permissions in ehcache.xml

---

uportal-war/src/main/resources/layout/theme/respondr/content.xsl

Replace the portlet maximized url by alternativeMaximizedLink when setted to open directly in a new browser tab. For master branch

UP-4775 : Use alternativeMaximizedLink into portlet-titlebar - master

---

uportal-war/src/main/resources/layout/theme/respondr/content.xsl

Replace the portlet maximized url by alternativeMaximizedLink when setted to open directly in a new browser tab.

UP-4775 : Use alternativeMaximizedLink into portlet-titlebar - rel-4-3-patches

---

uportal-war/src/main/java/org/apereo/portal/io/xml/portlet/PortletDefinitionImporterExporter.java
uportal-war/src/main/java/org/apereo/portal/portlet/container/services/PortletDefinitionPreferencesImpl.java
uportal-war/src/main/java/org/apereo/portal/portlet/dao/IPortletDefinitionDao.java
uportal-war/src/main/java/org/apereo/portal/portlet/dao/jpa/JpaPortletDefinitionDao.java
uportal-war/src/main/java/org/apereo/portal/portlet/dao/jpa/PortletDefinitionImpl.java
uportal-war/src/main/java/org/apereo/portal/portlet/registry/IPortletDefinitionRegistry.java
uportal-war/src/main/java/org/apereo/portal/portlet/registry/PortletDefinitionRegistryImpl.java
uportal-war/src/main/java/org/apereo/portal/portlets/portletadmin/PortletAdministrationHelper.java
uportal-war/src/main/java/org/apereo/portal/portlets/translator/PortletEntityTranslationController.java
uportal-war/src/test/groovy/org/apereo/portal/io/xml/portlet/PortletDefinitionImporterExporterTest.groovy
uportal-war/src/test/java/org/apereo/portal/portlet/dao/jpa/JpaMarketplaceRatingDaoTest.java
uportal-war/src/test/java/org/apereo/portal/portlet/dao/jpa/JpaPortletDaoTest.java
uportal-war/src/test/java/org/apereo/portal/portlet/registry/PortletEntityRegistryImplTest.java

…rtlet as a Tenant Admin user.

UP-4766: Fix tenant admin add portlet bug - master

---

uportal-war/src/main/java/org/jasig/portal/io/xml/portlet/PortletDefinitionImporterExporter.java
uportal-war/src/main/java/org/jasig/portal/portlet/container/services/PortletDefinitionPreferencesImpl.java
uportal-war/src/main/java/org/jasig/portal/portlet/dao/IPortletDefinitionDao.java
uportal-war/src/main/java/org/jasig/portal/portlet/dao/jpa/JpaPortletDefinitionDao.java
uportal-war/src/main/java/org/jasig/portal/portlet/dao/jpa/PortletDefinitionImpl.java
uportal-war/src/main/java/org/jasig/portal/portlet/registry/IPortletDefinitionRegistry.java
uportal-war/src/main/java/org/jasig/portal/portlet/registry/PortletDefinitionRegistryImpl.java
uportal-war/src/main/java/org/jasig/portal/portlets/portletadmin/PortletAdministrationHelper.java
uportal-war/src/main/java/org/jasig/portal/portlets/translator/PortletEntityTranslationController.java
uportal-war/src/test/groovy/org/jasig/portal/io/xml/portlet/PortletDefinitionImporterExporterTest.groovy
uportal-war/src/test/java/org/jasig/portal/portlet/dao/jpa/JpaMarketplaceRatingDaoTest.java
uportal-war/src/test/java/org/jasig/portal/portlet/dao/jpa/JpaPortletDaoTest.java
uportal-war/src/test/java/org/jasig/portal/portlet/registry/PortletEntityRegistryImplTest.java

…rtlet as a Tenant Admin user.

UP-4766: Fix tenant admin add portlet bug - rel-4-3-patches

---

uportal-war/src/main/webapp/WEB-INF/jsp/Favorites/view.jsp
uportal-war/src/main/webapp/media/skins/respondr/common/less/portlet.less

https://issues.jasig.org/browse/UP-4779

UP-4779:  Add an icon next to every item in the Favorites portlet

---

pom.xml

Improves logging and adds font awesome 4.7.

NOJIRA: Update resource-server - master

---

pom.xml

Improves logging and adds font awesome 4.7.

NOJIRA: Update resource-server - rel-4-3-patches

---

PULL_REQUEST_TEMPLATE.md

https://issues.jasig.org/browse/UP-4755
-   [x] [individual contributor license agreement](https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement) is signed
-   [x] commit message follows [commit guidelines](https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit)
Adds a Pull Request template that will automatically fill in when a PR is opened.
This template is based off the Node.js pull request template.
https://github.com/blog/2111-issue-and-pull-request-templates
https://github.com/nodejs/node/blob/master/.github/PULL_REQUEST_TEMPLATE.md

UP-4755: Add Pull Request Template

---

PULL_REQUEST_TEMPLATE.md

Use shorthand link references to make checklist more readable.

NOJIRA: Use link shorthand to make PR template more readable

---

README.md

Headers increase depth one level at a time. `#` -> `##` -> `###`
Files and filepaths are _italicized_.
Notes and notices are **bold**.
Literal links are wrapped in `<>`.
Code blocks are fenced with ``` and a language flag.
Blocks of different types are separated with a blank newline .
Reference:
https://daringfireball.net/projects/markdown/
https://github.com/wooorm/remark-lint/blob/master/doc/rules.md

NOJIRA: Apply consistent markdown formatting to README.md

---

uportal-war/src/main/resources/layout/theme/respondr/respondr.xsl

Set anchor url with Alternative Maximized Link on sitemap
PR for master

UP-4742: Use AlternativeMaximizedLink into sitemap - master

---

CONTRIBUTING.md
docs/README.md
docs/SUPPORTED_BROWSERS.md

Riffing on [uportal-dev@ discussion](https://groups.google.com/a/apereo.org/d/topic/uportal-dev/ipZKN9THoBM/discussion) of what browsers uPortal 5 ought to support.

Modernize supported browser documentation.

---

uportal-war/src/main/java/org/apereo/portal/security/provider/PersonImpl.java

Refactored `isGuest` method per https://github.com/Jasig/uPortal/pull/792#discussion_r94443431

NOJIRA: Refactor is guest

---

uportal-war/src/main/webapp/WEB-INF/flows/entity-selector/selectEntities.jsp
uportal-war/src/main/webapp/media/skins/common/javascript/uportal/entity-selector.js

https://issues.jasig.org/browse/UP-4787
Placeholder text in search box is not clearing when input is selected.
Clicking "Go" redirects to top level view instead of showing search results.
Change `<input>` value to placeholder.
update selector to look for `input[type=search]`. 

UP-4787:  Group editor fix - rel-4-3-patches

---

uportal-war/src/main/webapp/WEB-INF/flows/entity-selector/selectEntities.jsp
uportal-war/src/main/webapp/media/skins/common/javascript/uportal/entity-selector.js

https://issues.jasig.org/browse/UP-4787
Placeholder text in search box is not clearing when input is selected.
Clicking "Go" redirects to top level view instead of showing search results.
Change `<input>` value to placeholder.
update selector to look for `input[type=search]`. 

UP-4787: Group editor fix - master

---

uportal-war/src/main/webapp/WEB-INF/jsp/Invoker/login.jsp
uportal-war/src/main/webapp/WEB-INF/jsp/Invoker/logout.jsp

https://issues.jasig.org/browse/UP-4799
Adds icons to give some additional visual interest to the current plain text "login" and "logout"

UP-4799: Add sign in, sign out, and new user icons

---

README.md

Adds a summary of WCAG conformance and a link to most recent accessibility audit of uPortal.
This would be a candidate for cherry picking to `rel-4-3-patches`.

NOJIRA: Add accessibility summary in README

---

build.gradle

https://issues.jasig.org/browse/UP-4746
Enables the findbugs Gradle plugin.
``` sh
gradle findbugsMain
```

UP-4746: Add findbugs gradle plugin

---

package.json

https://issues.jasig.org/browse/UP-4750
Adds [Stylelint](https://github.com/stylelint/stylelint) checker for Less code style.
Adds [Stylelint Codestyle Standard](https://github.com/stylelint/stylelint-config-standard), which is based off google code style for css.

UP-4750: Setup StyleLint

---

PULL_REQUEST_TEMPLATE.md

[UP-4804](https://issues.jasig.org/browse/UP-4804)
Requests that developers add new phrases to the i18n messages.
Requests that developers check views using the WCAG 2.0 quick reference. …

UP-4804: Add internationalization and accessibility to PR checklist

---

uportal-war/src/main/resources/properties/groups/compositeGroupServices.xml
uportal-war/src/main/resources/properties/rdbm.properties
uportal-war/src/main/webapp/WEB-INF/flows/edit-group/viewGroupPermissions.jsp
uportal-war/src/main/webapp/WEB-INF/flows/edit-permission/editPermission.jsp
uportal-war/src/main/webapp/WEB-INF/flows/edit-portlet/choosePortlet.jsp
uportal-war/src/main/webapp/WEB-INF/flows/edit-portlet/chooseType.jsp
uportal-war/src/main/webapp/WEB-INF/flows/edit-portlet/configMode.jsp
uportal-war/src/main/webapp/WEB-INF/flows/edit-portlet/portletConfig.jsp
uportal-war/src/main/webapp/WEB-INF/flows/entity-selector/selectEntities.jsp
uportal-war/src/main/webapp/WEB-INF/flows/permissions-administration/deletePermission.jsp
uportal-war/src/main/webapp/WEB-INF/flows/permissions-administration/listActivities.jsp
uportal-war/src/main/webapp/WEB-INF/flows/permissions-administration/listOwners.jsp
uportal-war/src/main/webapp/WEB-INF/flows/permissions-administration/permissionLookupResult.jsp
uportal-war/src/main/webapp/WEB-INF/flows/permissions-administration/selectTarget.jsp
uportal-war/src/main/webapp/WEB-INF/flows/permissions-administration/showActivity.jsp
uportal-war/src/main/webapp/WEB-INF/flows/portlet-manager/confirmRemove.jsp
uportal-war/src/main/webapp/WEB-INF/flows/portlet-manager/listChannels.jsp
uportal-war/src/main/webapp/WEB-INF/flows/user-manager/confirmRemove.jsp
uportal-war/src/main/webapp/WEB-INF/flows/user-manager/viewPermissions.jsp
uportal-war/src/main/webapp/WEB-INF/jsp/Activity/activity.jsp
uportal-war/src/main/webapp/WEB-INF/jsp/PopularPortlets/listPortlets.jsp

Update broken links to ja-sig.org to closest modern equivalent link.

NOJIRA: Update broken links to ja-sig.org

---

uportal-war/src/main/webapp/media/skins/common/less/entity-selector.less
uportal-war/src/main/webapp/media/skins/respondr/common/less/content.less
uportal-war/src/main/webapp/media/skins/respondr/common/less/fluid_stopgap.less
uportal-war/src/main/webapp/media/skins/respondr/common/less/footer.less
uportal-war/src/main/webapp/media/skins/respondr/common/less/gallery.less
uportal-war/src/main/webapp/media/skins/respondr/common/less/tabs.less

First round of lint fixes based off #799.

UP-4750: Less code style cleanup - part 1

---

.travis.yml

This updates the Travis CI build to generate the project using the Java 8 compiler.

NOJIRA: Test uPortal 5 with Java 8 compiler

---

.travis.yml

This updates the Travis CI build to generate the project using the Java 7 and Java 8 compilers.

NOJIRA: Test uPortal 4 with Java 7 and 8 compilers

---

uportal-war/src/main/webapp/WEB-INF/jsp/BackgroundPreference/viewBackgroundPreference.jsp

https://issues.jasig.org/browse/UP-4791
Updates selector in Background Preference portlet to match with selector used by updated background.
Update JavaScript to switch background live rather than on page refresh.

UP-4791: Update background preference portlet to work with image filters

---

uportal-war/src/main/webapp/media/skins/respondr/common/less/content.less
uportal-war/src/main/webapp/media/skins/respondr/common/less/footer.less
uportal-war/src/main/webapp/media/skins/respondr/common/less/header.less
uportal-war/src/main/webapp/media/skins/respondr/common/less/navigation.less
uportal-war/src/main/webapp/media/skins/respondr/common/less/portlet.less
uportal-war/src/main/webapp/media/skins/respondr/common/less/tags.less
uportal-war/src/main/webapp/media/skins/respondr/defaultSkin/less/skin.less

https://issues.jasig.org/browse/UP-4796
Updates responsive breakpoints to use Bootstrap variables.
This improves readability and customizability of responsive utilities.

UP-4796: Leverage Bootstrap variables for responsive breakpoints

---

docs/README.md

Spelling fix "availabe" to "available".

NOJIRA: Spelling fix in docs README

---

README.md

| Version | Linux | Windows | Coverage |
| - | - | - | - |
| [uPortal 5](https://github.com/Jasig/uPortal/tree/master) | [![Linux Build Status](https://travis-ci.org/Jasig/uPortal.svg?branch=master)](https://travis-ci.org/Jasig/uPortal) | [![Windows Build Status](https://ci.appveyor.com/api/projects/status/8t95sjt090mf62dh/branch/master?svg=true)](https://ci.appveyor.com/project/drewwills/uportal/branch/master) | [![Coverage Status](https://coveralls.io/repos/github/Jasig/uPortal/badge.svg?branch=master)](https://coveralls.io/github/Jasig/uPortal?branch=master) |
| [uPortal …

NOJIRA: Add build status and code coverage matrix to README

---

pom.xml
uportal-war/src/main/resources/properties/contextOverrides/overridesContext.xml
uportal-war/src/main/resources/properties/contexts/mvcContext.xml
uportal-war/src/main/resources/properties/contexts/personDirectoryContext.xml
uportal-war/src/main/resources/properties/contexts/portlet/BackgroundPreference-portlet.xml
uportal-war/src/main/resources/properties/contexts/portlet/TenantManager-portlet.xml
uportal-war/src/main/resources/properties/contexts/securityContext.xml
uportal-war/src/main/resources/properties/contexts/servlet/mvcServletContext.xml
uportal-war/src/main/resources/properties/contexts/servlet/redirectionServletContext.xml

https://issues.jasig.org/browse/UP-4731
This is a reboot of @ChristianMurphy's PR for this ticket

UP-4731:  Update some dependency versions

---

docs/README.md
docs/redirect-guest-to-cas.md

Adding missing documentation on guest redirect

NOJIRA: Add documentation on redirecting guests to sign-in.

---

docs/configure-using-jndi.md

Add details on CAS JNDI configuration to JNDI doc

NOJIRA: Add CAS JNDI filter configuration documentation.

---

appveyor.yml

Remove unneeded setup instructions.
Increase the build matrix to test all permutations of:
Java 7 and Java 8
Windows Server 2012 R2 and Windows Server 2016

NOJIRA: Appveyor update rel-4-3-patches

---

README.md

[UP-4698](https://issues.jasig.org/browse/UP-4698)
| Version | Linux | Windows | Coverage | Dependencies |
| - | - | - | - | - |
| [uPortal 5](https://github.com/Jasig/uPortal/tree/master) | [![Linux Build Status](https://travis-ci.org/Jasig/uPortal.svg?branch=master)](https://travis-ci.org/Jasig/uPortal) | [![Windows Build Status](https://ci.appveyor.com/api/projects/status/8t95sjt090mf62dh/branch/master?svg=true)](https://ci.appveyor.com/project/drewwills/uportal/branch/master) | [![Coverage Status](https://coveralls.io/repos/github/Jasig/uPortal/badge.svg?branch=master)](https://coveralls.io/github/Jasig/uPortal?branch=master) …

UP-4698: Add version eye badge

---

README.md

Reverts Jasig/uPortal#838 pending related PR merge

Revert "UP-4698: Add version eye badge"

---

appveyor.yml

Ensure tests are run on windows server 2016 (previously they were run on server 2012 R2).
Include maven tests are part of test process.

NOJIRA: Simplify appveyor testing and include maven tests on master

---

README.md

<table><tr>
<td>
[![WCAG 2 AA Badge](https://www.w3.org/WAI/wcag2AA-blue-v.svg)](#accessible)
[![Issue Stats](http://issuestats.com/github/Jasig/uPortal/badge/pr)](http://issuestats.com/github/Jasig/uPortal)
[![Google Code Style](https://img.shields.io/badge/code_style-Google-green.svg?style=flat)](https://google.github.io/styleguide/javaguide.html)
| Version | Linux | Windows | Coverage |
| - | - | - | - |
| [uPortal 5](https://github.com/Jasig/uPortal/tree/master) | [![Linux Build Status](https://travis-ci.org/Jasig/uPortal.svg?branch=master)](https://travis-ci.org/Jasig/uPortal) | [![Windows Build …

NOJIRA: Add additional badges

---

pom.xml
uportal-war/src/main/java/org/apereo/portal/groups/CompositeEntityIdentifier.java
uportal-war/src/main/java/org/apereo/portal/io/xml/subscribedfragment/SubscribedFragmentImporterExporter.java
uportal-war/src/main/java/org/apereo/portal/utils/MySQL5InnoDBCompressedDialect.java

Adds improved Java 8 support and a variety of new bug types detected.
This also includes a few of the quick and easy to resolve recommendations given by Findbugs.

UP-4832: Update Findbugs Maven plugin version from 2 to 3

---

uportal-war/src/main/java/org/apereo/portal/layout/dlm/remoting/UpdatePreferencesServlet.java

Adds a remove by fname action to the /layout servlet

UP-4837 adding removeByFName

---

uPortal-soffit/uPortal-soffit-connector/src/main/java/org/apereo/portal/soffit/connector/SoffitConnectorController.java

https://issues.jasig.org/browse/UP-4828
wrapping EntityUtils.consumeQuietly in finally block of SoffitConnectorController

UP-4828 wrapping entity consume in finally

---

pom.xml
uportal-war/src/main/webapp/media/skins/respondr/common/common_skin.xml

Updates version of underscore used by uPortal.

UP-4839: Update underscore version in uPortal

---

docs/ACCESSIBILITY.md
docs/README.md

<https://issues.jasig.org/browse/UP-4840>
Copy documentation from https://wiki.jasig.org/display/UPC/Accessibility+Guidelines into the uPortal 5 manual.
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cf …

UP-4840: Add accessibility page to uPortal 5 manual

---

uportal-war/src/test/java/org/apereo/portal/groups/pags/testers/InjectAttributeRegexTesterTest.java

https://issues.jasig.org/browse/UP-4843
Random string generator was occasionally having some identical string collisions.
This replaces random string generator with UUID which is more random.

UP-4843: Stabilize flaky InjectAttributeRegexTesterTest

---

uportal-war/src/main/resources/layout/theme/respondr/navigation.xsl
uportal-war/src/main/resources/layout/theme/respondr/regions.xsl
uportal-war/src/main/resources/layout/theme/respondr/respondr.xsl
uportal-war/src/main/webapp/media/skins/respondr/common/less/header.less

https://issues.jasig.org/browse/UP-4850
This is a slight modification of #882 and applied to the `master` branch.

UP-4850:  Add 'Skip to page content' button in the portal header

---

build.gradle
gradle/tasks/clean.gradle
gradle/tasks/hsql.gradle

-   [ ] the [individual contributor license agreement][] is signed
Clean up of new Gradle tasks to bring in line with conventions.

NOJIRA: Clean up Gradle tasks

---

gradle/tasks/clean.gradle
gradle/tasks/hsql.gradle

Improve accuracy of some Gradle tasks.

NOJIRA: Refine Gradle tasks that clean Tomcat.

---

.gitignore
docs/installing/building-and-deploying.md
docs/installing/database/db2.md
docs/installing/database/index.md
docs/installing/downloading.md
docs/installing/index.md
docs/installing/requirements.md
docs/installing/tomcat/fronting-with-httpd.md
docs/installing/tomcat/index.md
docs/installing/tomcat/ssl-configuration.md

Naive incomplete porting forward of some of the uPortal 4.3 in-Confluence-wiki documentation into `/docs`.
I'd had this branch hanging out locally for a while; this PR is a way to share, make visible this partial progress.
-----
Checklist
-   [ ] commit message follows [commit guidelines][] (Catch this in squash merge.)

Port in a bit of the Confluence documentation

---

build.gradle

> Automatically chooses between snarl, growl, and notify-send depending on the current operating system.

NOJIRA: Show notification when gradle script has finished

---

build.gradle

Bundles dependencies from all 50+ sub-projects into a single report,
allowing the entire uPortal project to be scanned under the free plan.

NOJIRA: Add gradle version eye plugin

---

build.gradle

-   [x ] the [individual contributor license agreement][] is signed
For some reason the ability to publish to maven local was removed. I added it back

NOJIRA: Can now publish to local maven

---

.travis.yml

Test uPortal version 4.3 across
OS:
* Ubuntu Trusty :new:
* Ubuntu Precise
* OS X 10.12 :new:
* OS X 10.11 :new: 
* OS X 10.10 :new:
* Windows server 2016 
* Windows server 2012 R2
Java:
* Oracle JDK 8
* Oracle JDK 7
* Open JDK 7
[WCAG 2.0 AA]: …

NOJIRA: Test on Ubuntu trusty and precise, test on macOS

---

docs/sysadmin/F5-load-balancer.md

F5 Load Balancer Documentation

---

uPortal-api/uPortal-api-rest/src/test/java/org/apereo/portal/org/apereo/portal/security/remoting/PermissionAssignmentMapControllerTest.java
uPortal-api/uPortal-api-rest/src/test/java/org/apereo/portal/org/apereo/portal/security/remoting/PermissionsListControllerTest.java
uPortal-api/uPortal-api-rest/src/test/java/org/apereo/portal/rest/PagsRESTControllerTest.java
uPortal-api/uPortal-api-rest/src/test/java/org/apereo/portal/rest/layout/LayoutJsonV1RenderingControllerTest.java
uPortal-api/uPortal-api-rest/src/test/java/org/apereo/portal/rest/layout/LayoutJsonV43RenderingControllerTest.java
uPortal-api/uPortal-api-rest/src/test/java/org/apereo/portal/rest/layout/TabListOfNodesTest.java

-   [X] tests are included
Added unit test for package - Added unit test for org.apereo.portal.security.remoting package
Jira ticket - https://issues.jasig.org/browse/UP-4884 …

UP-4884: add unit test portal security remoting

---

uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/entity-selector.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/jsr-168.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/portal-admin.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/portlet.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/tabs.less

Replace hardcoded colors with uPortal color palette variable to make creating a theme easier.

NOJIRA: Replace hardcoded less colors with the uPortal color palette

---

README.md
docs/README.md

https://groups.google.com/a/apereo.org/d/topic/uportal-dev/ZZlBH8wsVAM/discussion
<a href="https://github.com/search?q=topic%3Auportal+topic%3Asoffit&type=Repositories">
</a>
<a href="https://github.com/search?q=topic%3Auportal+topic%3Aportlet&type=Repositories">
</a>
[WCAG 2.0 AA]: …

NOJIRA: Add badges to discover community soffits and portlets

---

build.gradle
package-lock.json
package.json
uPortal-webapp/package-lock.json

Includes newer faster version of the node package manager.
Improves the lockfile mechanism.
:notebook: to update local node version run `./gradlew npm_install`

NOJIRA: Update Node js from version 8.0.0 to 8.1.4

---

uportal-war/src/main/resources/properties/i18n/Messages.properties
uportal-war/src/main/webapp/WEB-INF/jsp/Marketplace/portlet/entry.jsp
uportal-war/src/main/webapp/WEB-INF/jsp/Marketplace/portlet/view.jsp
uportal-war/src/main/webapp/media/skins/respondr/common/bootstrap/variables.less
uportal-war/src/main/webapp/media/skins/respondr/defaultSkin/less/variables.less

https://issues.jasig.org/browse/UP-4877
- Added role to table headers and added header. Also added caption.
- Added alt attribute to icons.
- Changed the options list and added rule to each item..
- Added a css specification to darken the disabled text.
- Added aria attributes where necessary.
- Improved accessibility to dialog.
- Improved overflowing issues. …

UP-4877: Improving ADA for Marketplace

---

package-lock.json
package.json

Part 1 of the follow up to #842.
Updates the linters but does not make them a breaking part of the build yet, or resolve any of the lint warnings.

UP-4819: Update Markdown, JavaScript, and Sass linters

---

SUPPORT.md

Adapted from the Angular support file. https://github.com/angular/angular-cli/pull/7082
See https://github.com/blog/2400-support-file-support for github support.

NOJIRA: Add a SUPPORT.md file to guide questions to the mailing list

---

README.md

Updated readme as per UP-4914 to reflect uPortal5 build changes.

UP-4914 Revised readme for uPortal5

---

uPortal-webapp/src/main/resources/org/apereo/portal/tenants/sampledata/portlet-definition/skin.portlet-definition.xml

Use apps/preferences-desktop-theme.png instead of actions/preferences-desktop-theme.png
@see https://github.com/Jasig/resource-server/blob/master/resource-server-content/src/main/webapp/rs/tango/0.8.90/32x32/apps/preferences-desktop-theme.png

NOJIRA: Fix HTTP 404 on tenants skin.portlet-definition.xml

---

docs/README.md
docs/css/reset_image_size.css

Allows badges on home page to render normally.
Before:
After:

NOJIRA: Reset image sizing adjusted by jekyll dinky theme

---

uportal-war/src/main/java/org/jasig/portal/portlet/registry/PortletDefinitionRegistryImpl.java

Corrected minor typo in PortletDefinitionRegistryImpl
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2 …

NOJIRA Corrected minor typo - rel-4-3-patches

---

uPortal-rendering/src/main/java/org/apereo/portal/portlet/registry/PortletDefinitionRegistryImpl.java

Corrected minor typo in PortletDefinitionRegistryImpl
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2 …

NOJIRA Corrected minor typo in PortletDefinitionRegistryImpl

---

uportal-war/src/main/java/org/jasig/portal/url/UrlCanonicalizingFilter.java

-   [ x] the [individual contributor license agreement][] is signed
Cookie is now secure and httponly

UrlCanonicalizingFilter.REDIRECT_COUNT is secure and httponly

---

uPortal-api/uPortal-api-internal/src/test/java/org/apereo/portal/portlets/account/GroupedPersonAttrByNameComparatorTest.java
uPortal-api/uPortal-api-internal/src/test/java/org/apereo/portal/portlets/account/UserAccountHelperTest.java

Adding new unit test cases for org.apereo.portal.portlets.account package
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies= …

UP-4929 : Build unit test cases for org.apereo.portal.portlets.account

---

uPortal-webapp/src/main/resources/properties/contexts/datasourceContext.xml
uPortal-webapp/src/main/resources/properties/contexts/ldapContext.xml
uPortal-webapp/src/main/resources/properties/portal.properties
uPortal-webapp/src/main/resources/properties/rdbm.properties

https://issues.jasig.org/browse/UP-4943

UP-4943: Set DB and LDAP pool values via properties

---

uPortal-webapp/src/main/resources/properties/contexts/applicationContext.xml

-   [ x] the [individual contributor license agreement][] is signed
Allows jgroups to be used in a PostgreSQL environment

Added jgroups support for PostgreSQL

---

uPortal-webapp/src/main/resources/properties/contexts/applicationContext.xml
uPortal-webapp/src/main/resources/properties/jgroups.xml
uPortal-webapp/src/main/resources/properties/portal.properties

https://issues.jasig.org/browse/UP-4949

UP-4949: Initial JGroups stack change with Toben's changes included.

---

build.gradle

use plain semantic version tag without any prefixing.
This makes automated version checking simpler, since it matches the semver regex.
https://github.com/sindresorhus/semver-regex/blob/master/index.js#L3
*edit* SemVerTag does encourage using a `v` prefix
[WCAG 2.0 AA]: …

refactor: release tag

---

.travis.yml
README.md
docs/README.md
gradle.properties

[![Dependency Status](https://www.versioneye.com/user/projects/59e525762de28c000f9188ae/badge.svg?style=flat-square)](https://www.versioneye.com/user/projects/59e525762de28c000f9188ae)
Gives up-to-date status on the status and security of libraries used by uPortal.
[WCAG 2.0 AA]: …

VersionEye Status

---

docs/implement/README.md
docs/implement/security.md
uPortal-security/uPortal-security-mvc/src/main/java/org/apereo/portal/security/filter/CorsFilter.java
uPortal-webapp/src/main/resources/properties/contexts/securityContext.xml
uPortal-webapp/src/main/resources/properties/security.properties
uPortal-webapp/src/main/webapp/WEB-INF/web.xml

https://issues.jasig.org/browse/UP-4957

UP-4957: CORS Filter

---

build.gradle
config/codenarc/codenarc.xml
gradle.properties
uPortal-api/uPortal-api-rest/build.gradle
uPortal-events/build.gradle
uPortal-groups/uPortal-groups-ldap/build.gradle
uPortal-groups/uPortal-groups-smartldap/build.gradle
uPortal-io/uPortal-io-types/build.gradle
uPortal-portlets/build.gradle
uPortal-rdbm/build.gradle
uPortal-rendering/build.gradle
uPortal-security/uPortal-security-authn/build.gradle
uPortal-soffit/uPortal-soffit-renderer/build.gradle
uPortal-utils/uPortal-utils-core/build.gradle
uPortal-web/build.gradle
uPortal-webapp/build.gradle
uPortal-webapp/src/test/groovy/org/apereo/portal/io/xml/portlet/PortletDefinitionImporterExporterTest.groovy
uPortal-webapp/src/test/groovy/org/apereo/portal/rendering/PortletDefinitionAttributeSourceTest.groovy

https://issues.jasig.org/browse/UP-4903
Bring automatic static analysis and recommendations for groovy files.

Test: codenarc

---

bootstrap/hsqldb/pom.xml
bootstrap/pluto-assembler/pom.xml
bootstrap/pom.xml
bootstrap/uportal-ant-tasks/pom.xml
pom.xml
uportal-db/pom.xml
uportal-ear/pom.xml
uportal-platform-api/pom.xml
uportal-portlets-overlay/AnnouncementsPortlet/pom.xml
uportal-portlets-overlay/BookmarksPortlet/pom.xml
uportal-portlets-overlay/CalendarPortlet/pom.xml
uportal-portlets-overlay/FunctionalTestsPortlet/pom.xml
uportal-portlets-overlay/NewsReaderPortlet/pom.xml
uportal-portlets-overlay/NotificationPortlet/pom.xml
uportal-portlets-overlay/SimpleContentPortlet/pom.xml
uportal-portlets-overlay/WeatherPortlet/pom.xml
uportal-portlets-overlay/WebProxyPortlet/pom.xml
uportal-portlets-overlay/basiclti-portlet/pom.xml
uportal-portlets-overlay/cas-proxy-test-portlet/pom.xml
uportal-portlets-overlay/cas/pom.xml
uportal-portlets-overlay/email-preview/pom.xml
uportal-portlets-overlay/jasig-widget-portlets/pom.xml
uportal-portlets-overlay/pluto-testsuite/pom.xml
uportal-portlets-overlay/pom.xml
uportal-portlets-overlay/sakai-connector-portlet/pom.xml
uportal-search-api/pom.xml
uportal-war/pom.xml

Bumped versions to 4.3.3-SNAPSHOT

Bumped versions to 4.3.3-SNAPSHOT

---

README.md
docs/README.md

Add links to uPortal-dev and uPortal-user mailing lists.
Add link to Apereo slack channel.
Remove links to irc and gitter, there is no longer much energy in these channels.
Ref: https://groups.google.com/a/apereo.org/d/msg/uportal-dev/sy8NvU25mQA/zGQ26HkqCwAJ
<table>
<tr>
<th>
Get Involved
</th>
<th>
Outlet
</th>
</tr>
<tr>
<td>
Report an Issue
</td>
<td>
<a href="https://issues.jasig.org/browse/UP">
</a>
</td>
</tr>
<tr>
<td>
Request a feature
</td>
<td>
<a href="https://issues.jasig.org/browse/UP">
</a>
</td>
</tr>
<tr>
<td>
Contribute Code
</td>
<td>
<a href="CONTRIBUTING.md">
</a>
</td>
</tr>
<tr>
<td>
Join the Conversation …

docs: update links to discussion channels for uPortal

---

docs/README.md

somehow brace got missed when copying from */README.md* to
*/docs/README.md*, re-adding so document renders correctly.

docs: add mixing closing brace in badges

---

uPortal-webapp/src/main/webapp/WEB-INF/jsp/Favorites/view.jsp
uPortal-webapp/src/main/webapp/WEB-INF/jsp/Favorites/view_zero.jsp
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/portlet.less

https://issues.jasig.org/browse/UP-4968

UP-4968:  Add Bootstrap styling to the empty favorites view

---

uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/dlm/PLFIntegrator.java
uPortal-layout/uPortal-layout-impl/src/main/java/org/apereo/portal/layout/dlm/PositionManager.java

-   [ ] the [individual contributor license agreement][] is signed
https://issues.jasig.org/browse/UP-4974

UP-4974: Fix handling of node marker removal in PositionManager.

---

CONTRIBUTING.md
README.md

* link to additional resource on rebasing
* add code fence around terminal examples
* include information on unit testing in testing section
* corrected link to uPortal-user mail list

docs(contributing): link to additional resources on contributing

---

.travis.yml
README.md
build.gradle
docs/README.md
gradle.properties

See: https://groups.google.com/a/apereo.org/d/msg/uportal-dev/lhgtquVXZLM/-hB9iRNOAAAJ

refactor: remove VersionEye

---

README.md
docs/README.md

<table border="0">
<tr>
<td>
<a href="https://www.w3.org/TR/WCAG20/">
</a>
<a href="http://issuestats.com/github/Jasig/uPortal">
</a>
<a href="https://google.github.io/styleguide/javaguide.html">
</a>
<a href="https://github.com/search?q=topic%3Auportal+topic%3Asoffit&type=Repositories">
</a>
<a href="https://github.com/search?q=topic%3Auportal+topic%3Aportlet&type=Repositories">
</a>
<br>
<table>
<tr>
<th>
Version
</th>
<th>
Linux
</th>
<th>
Windows
</th>
<th>
Coverage
</th>
</tr>
<tr>
<td>
<a href="https://github.com/Jasig/uPortal/tree/master">
uPortal 5.1
</a>
</td>
<td>
<a href="https://travis-ci.org/Jasig/uPortal">
</a> …

docs(readme): show uPortal 5.0 and uPortal 5.1 in status badges

---

.travis.yml
appveyor.yml
docs/developer/other/RELEASE.md

daemon adds to memory usage on CI which slows the builds down.
parallel mode isn't improving build time and can cause ci logs to get scrambled.

ci: reduce memory usage

---

.travis.yml

Same as https://github.com/Jasig/uPortal/pull/1109
Backporting this to `rel-4-3-patches` requires some special care due to differences in CI matrix.

ci(travis): include ubuntu xenial in test matrix - rel-4-3-patches

---

docs/fr/ACCESSIBILITE.md
docs/fr/COMMITTERS.md
docs/fr/NAVIGATEURS_SUPPORTES.md
docs/fr/README.md
docs/fr/developper/README.md
docs/fr/developper/other/ARCHITECTURE.md
docs/fr/developper/other/DEPLOIEMENT.md
docs/fr/developper/other/INTEGRATION_IDE.md
docs/fr/developper/soffits/README.md
docs/fr/developper/soffits/options-de-configuration.md
docs/fr/developper/soffits/publier_une_soffit.md
docs/fr/developper/soffits/soffit_minimale.md
docs/fr/developper/soffits/soffit_modele_de_donnee.md
docs/fr/implementer/README.md
docs/fr/implementer/authentification/README.md
docs/fr/implementer/authentification/cas.md
docs/fr/implementer/frontend/README.md
docs/fr/implementer/frontend/RENDERING_PIPELINE.md
docs/fr/implementer/frontend/SKIN_UPORTAL.md
docs/fr/implementer/frontend/USING_ANGULAR_fr.md
docs/fr/implementer/securite.md
docs/fr/implementer/user-attributes/README.md
docs/fr/implementer/user-attributes/jdbc.md
docs/fr/implementer/user-attributes/ldap.md
docs/fr/monter-et-deployer-uportal.md
docs/fr/sysadmin/F5-load-balancer.md
docs/fr/sysadmin/README.md
docs/fr/usage-de-jndi.md

-   [X ] the [individual contributor license agreement][] is signed
-   [X ] documentation is changed or added
Provide the french documentation for uPortal 5.1 reviewed by Julien Gribonwald.
Every spellings are fixed and everything is now updated with 5.1.
I've got pb with my previous PR locally, so it was simpler for me to create a new PR.
Many Thanks to Julien for the review.
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#co …

UP-4956 Add French Documentation reviewed

---

docs/fr/ACCESSIBILITE.md
docs/fr/COMMITTERS.md
docs/fr/NAVIGATEURS_SUPPORTES.md
docs/fr/README.md
docs/fr/developper/other/DEPLOIEMENT.md
docs/fr/developper/other/INTEGRATION_IDE.md
docs/fr/developper/soffits/options-de-configuration.md
docs/fr/developper/soffits/publier_une_soffit.md
docs/fr/developper/soffits/soffit_minimale.md
docs/fr/implementer/authentification/cas.md
docs/fr/implementer/frontend/RENDERING_PIPELINE.md
docs/fr/implementer/frontend/SKIN_UPORTAL.md
docs/fr/implementer/frontend/USING_ANGULAR_fr.md
docs/fr/implementer/securite.md
docs/fr/monter-et-deployer-uportal.md
docs/fr/sysadmin/F5-load-balancer.md

- Fix all spelling reviewed by Julien Gribonwald in [pull1111](https://github.com/Jasig/uPortal/pull/1111#pullrequestreview-88221886)
- Fix path of images files and CSS files
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/reso …

UP-4956 [doc] Add French Documentation reviewed - take 2

---

gradle.properties
package-lock.json
package.json
uPortal-webapp/package-lock.json
uPortal-webapp/package.json

Updates Node.js to latest LTS to take advantage of [cross platform package management improvements](https://github.com/npm/npm/blob/latest/CHANGELOG.md#v560-2017-11-27).
Libraries are updated to latest minor versions.
Tested locally, tree based selection appears to be working fine, and less compilation looks good.
[WCAG 2.0 AA]: …

chore: update javascript dependencies

---

gradle.properties

updates ant to the latest version.

chore: update ant to version 1.10.1

---

docs/fr/developper/README.md
docs/fr/developper/other/API.md

Update of the french :fr: Documentation : API.md
See UP-4992.
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2 …

[DOC] Update french Documentation API ref UP-4992

---

gradle.properties

Updates portlet utils to latest version.

chore: update portlet utils to version 1.1.2

---

gradle.properties

updates aws java sdk to latest version.

chore: update aws java sdk to version 1.11.255

---

docs/fr/implementer/authentification/README.md
docs/fr/implementer/authentification/REMOTE_USER.md

Update french Documentation :fr:  for REMOTE_USER AuthN
ref UP-4993
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2 …

[DOC] Update french Documentation REMOTE_USER AuthN ref UP-4993

---

.travis.yml
package.json
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/entity-selector.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/flyout-nav.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-autocomplete.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-config-lightbox.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-entity-registry.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-favorite.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-fragment-permissions-manager.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-ga.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-layout-draggable-manager.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-layout-gallery.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-layout-persistence.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-layout-preferences.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-layout-selector.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-parameter-editor.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-portlet-browser.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-portlet-registry.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-print-plugin.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-rating-option.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-showHideToggle.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-skin-selector.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-tab-manager.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-translator.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-url-provider.js
uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-util.js
uPortal-webapp/src/main/webapp/media/skins/respondr/common/javascript/uportal/fluid-jquery-compatibility.js
uPortal-webapp/src/main/webapp/rs/conflict-resolution/js/resolve-conflicts.js
uPortal-webapp/src/main/webapp/scripts/search/autosuggestHandler.js
uPortal-webapp/src/main/webapp/scripts/session-timeout.js

most of the code cleanup was automated with prettier-eslint, configured to use the google code style.

style(javascript): Apply Google code style to JavaScript

---

build.gradle

Removed duplicate maven-publish apply

---

build.gradle

https://github.com/google/error-prone/releases/tag/v2.2.0

chore(deps): update error prone to version 2.2.0

---

build.gradle

https://github.com/nebula-plugins/gradle-lint-plugin/releases/tag/v8.3.2

chore(gradle): update gradle lint to version 8.3.2

---

build.gradle

https://github.com/CodeNarc/CodeNarc/blob/master/CHANGELOG.md#version-11-jan-2018

chore(deps): update codenarc to version 1.1

---

gradle.properties

https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111285-2018-02-23

chore(deps): update aws sdk to version 2.11.285

---

gradle.properties

updates woodstock to latest version.

chore: update woodstock to version 4.4.1

---

uPortal-webapp/src/main/resources/properties/contexts/securityContext.xml

https://issues.jasig.org/browse/UP-5000

UP-5000 Revised ticketValidationFilter bean to use serverName instead of service

---

gradle.properties

https://github.com/Jasig/portlet-utils/releases/tag/portlet-utils-parent-1.1.3

chore: update portlet utils to version 1.1.3

---

uportal-war/src/main/java/org/jasig/portal/portlets/marketplace/PortletMarketplaceController.java

bug(UP-5006): check initialFilter value is a valid category for uP4.

---

gradle.properties

https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111297-2018-03-16

chore(deps): AWS SDK version 1.11.297

---

package-lock.json
package.json
uPortal-webapp/package-lock.json

chore(deps): update javascript modules

---

docs/GLOSSARY.md
docs/README.md

Based on feedback uPortal, uPortal still has jargon that takes getting used to.
The glossary is designed as a place to put definitions for uPortal-isms to help keep the project easy to get started with and interact with.
[WCAG 2.0 AA]: …

docs(glossary): add a starting document for a glossary of uPortal-isms

---

uPortal-webapp/src/main/resources/properties/contexts/securityContext.xml

doc(cors): Add comment on format for allowedOrigins

---

docs/sysadmin/F5-load-balancer.md

doc(F5): Add documentation for Remote IP Valve

---

docs/fr/README.md

Add links to uPortal 5.0 french docs in docs/fr/readme.md
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cfla …

docs-fr: add links to uPortal 5.0 french docs

---

gradle/wrapper/gradle-wrapper.properties

chore(gradle): update gradle wrapper to version 4.7

---

gradle.properties

chore(deps): update ant to version 1.10.3

---

gradle.properties

https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111320-2018-04-30

chore(deps): update AWS SDK to version 1.11.320

---

build.gradle

build scan plugin changes:
https://plugins.gradle.org/plugin/com.gradle.build-scan/1.9.1
https://plugins.gradle.org/plugin/com.gradle.build-scan/1.10
https://plugins.gradle.org/plugin/com.gradle.build-scan/1.10.1
https://plugins.gradle.org/plugin/com.gradle.build-scan/1.10.2
https://plugins.gradle.org/plugin/com.gradle.build-scan/1.10.3
https://plugins.gradle.org/plugin/com.gradle.build-scan/1.11
https://plugins.gradle.org/plugin/com.gradle.build-scan/1.12
https://plugins.gradle.org/plugin/com.gradle.build-scan/1.12.1
https://plugins.gradle.org/plugin/com.gradle.build-scan/1.13
https://plugins.gradle.org/plugin/com.gradle.build-scan/1.13.1
release plugin changes: …

chore(deps): update gradle plugins

---

README.md
docs/README.md

Adds links to uPortal 5.1.0 documentation and 5.2.0 documentation

docs(readme): add links to uPortal 5.1.0 docs and 5.2.0 docs

---

uPortal-content/uPortal-content-portlet/src/main/java/org/apereo/portal/portlet/dao/jpa/PortletDefinitionImpl.java
uPortal-content/uPortal-content-portlet/src/main/java/org/apereo/portal/portlet/dao/jpa/PortletDefinitionParameterImpl.java

This change set implements the same algorithm (gets the same results) in fewer lines of code.
-   [ ] commit message follows [commit guidelines][] (roughly, conventional commits)
-   N/A documentation is changed or added
-   N/A view conforms with [WCAG 2.0 AA][]
[WCAG 2.0 AA]: …

refactor: same hashCode() algorithm with less ceremony

---

gradle.properties

Other releases can continue on
* rel-4-3-patches
* rel-5-0-patches
* rel-5-1-patches
master is now working toward uPortal 5.2.0

chore: prepare uPortal 5.2.0 snapshot

---

gradle.properties

chore: update AWS SDK to version 1.11.333

---

docs/developer/soffits/securing_apis.md

Corrected minor typo in docs/developer/soffits/securing_apis.md

---

uPortal-webapp/package-lock.json
uPortal-webapp/package.json

https://github.com/less/less.js/blob/master/CHANGELOG.md#300

chore(deps): upgrade less js to version 3.0.4

---

gradle.properties

https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111341-2018-06-04

chore: update aws sdk java to version 1.11.341

---

gradle.properties

https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111350-2018-06-19

chore(deps): update aws sdk java to version 1.11.350

---

build.gradle
gradle.properties

https://github.com/xmlunit/xmlunit/blob/master/RELEASE_NOTES.md#xmlunit-for-java-260---released-2018-04-22

chore(deps): update xmlunit to version 2.6.0

---

CONTRIBUTING.md
PULL_REQUEST_TEMPLATE.md
README.md
docs/README.md
gradle.properties

Corrected references to Jira issue tracker to point to GitHub issues.

docs: update documentation to point to GitHub issue tracker

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Give two templates for creating an issue.
One for creating a bug report, focusing on collecting details needed to reproduce the issue.
One for creating a feature request, focused on collecting motivation for change and a range of potential solutions.
[WCAG 2.0 AA]: …

docs: create an issue template for bug reports and feature requests

---

gradle.properties
uPortal-concurrency/build.gradle
uPortal-rendering/src/main/java/org/apereo/portal/portlet/registry/PortletEntityRegistryImpl.java

Based on a conversation with @drewwills, this dependency is no longer needed.

refactor: drop commons collections as a top level dependency

---

gradle.properties
uPortal-utils/uPortal-utils-core/build.gradle

https://github.com/FasterXML/woodstox/blob/master/release-notes/VERSION

chore: upgrade woodstox to version 5.1.0

---

gradle.properties

https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111357-2018-06-28

chore: update aws sdk java to version 1.11.357

---

gradle.properties

Version number is not used by the gradle build anymore.

chore: removed unused dependency jline

---

build.gradle

https://github.com/nebula-plugins/gradle-lint-plugin/releases/tag/v9.3.3
https://github.com/nebula-plugins/gradle-lint-plugin/releases/tag/v9.3.4

chore: update gradle lint to version 9.3.4

---

README.md
docs/README.md

Update link to 5.1.x documentation to point to 5.1.2.
Give each badge in table its own newline.

Docs: update readme

---

uPortal-groups/uPortal-groups-filesystem/src/main/java/org/apereo/portal/groups/filesystem/FileSystemGroupStore.java
uPortal-portlets/src/main/java/org/apereo/portal/portlets/dynamicskin/storage/AbstractDynamicSkinService.java
uPortal-security/uPortal-security-authn/src/main/java/org/apereo/portal/security/provider/CacheSecurityContext.java
uPortal-security/uPortal-security-authn/src/main/java/org/apereo/portal/security/provider/SimpleSecurityContext.java
uPortal-security/uPortal-security-authn/src/main/java/org/apereo/portal/security/provider/cas/CasAssertionSecurityContext.java
uPortal-security/uPortal-security-authn/src/main/java/org/apereo/portal/security/provider/cas/clearpass/PasswordCachingCasAssertionSecurityContext.java
uPortal-tools/src/main/java/org/apereo/portal/security/CliPasswordUpdateTool.java
uPortal-tools/src/main/java/org/apereo/portal/shell/PortalShell.java
uPortal-tools/src/main/java/org/apereo/portal/tools/dbloader/DataSourceSchemaExport.java
uPortal-utils/uPortal-utils-core/src/main/java/org/apereo/portal/utils/ResourceLoader.java

Automated by http://errorprone.info/bugpattern/DefaultCharset

refactor: add default character set to read operations

---

README.md
docs/README.md

docs: add rel 5.2 to build matrix

---

uPortal-groups/uPortal-groups-filesystem/src/main/java/org/apereo/portal/groups/filesystem/FileSystemGroupStoreFactory.java
uPortal-groups/uPortal-groups-pags/src/test/java/org/apereo/portal/groups/pags/PAGSTest.java
uPortal-rendering/src/test/java/org/apereo/portal/portlet/container/properties/MockRequestPropertiesManager.java
uPortal-security/uPortal-security-authn/src/test/java/org/apereo/portal/security/provider/cas/CasSecurityContextMock.java
uPortal-security/uPortal-security-authn/src/test/java/org/apereo/portal/security/provider/cas/CasSecurityContextMockTest.java
uPortal-spring/src/test/java/org/apereo/portal/spring/security/preauth/PortalPreAuthenticatedProcessingFilterIdentitySwapTest.java
uPortal-spring/src/test/java/org/apereo/portal/spring/security/preauth/PortalPreAuthenticatedProcessingFilterIdentityUnswapTest.java
uPortal-spring/src/test/java/org/apereo/portal/spring/security/preauth/PortalPreAuthenticatedProcessingFilterTest.java
uPortal-webapp/src/test/java/org/apereo/portal/concurrency/locking/EntityLockTest.java
uPortal-webapp/src/test/java/org/apereo/portal/events/AnalyticsIncorporationComponentEventSerializationTest.java
uPortal-webapp/src/test/java/org/apereo/portal/groups/GroupsTester.java
uPortal-webapp/src/test/java/org/apereo/portal/groups/PersonDirNameFinderTest.java
uPortal-webapp/src/test/java/org/apereo/portal/mock/portlet/om/MockPortletDefinitionId.java
uPortal-webapp/src/test/java/org/apereo/portal/mock/portlet/om/MockPortletEntityId.java
uPortal-webapp/src/test/java/org/apereo/portal/mock/portlet/om/MockPortletWindowId.java
uPortal-webapp/src/test/java/org/apereo/portal/security/provider/AuthorizationTester.java
uPortal-webapp/src/test/java/org/apereo/portal/test/PortalJpaInterceptor.java
uPortal-webapp/src/test/java/org/apereo/portal/utils/threading/DynamicThreadPoolExecutorTest.java

style: add override annotations to tests

---

config/codenarc/codenarc.xml

http://codenarc.sourceforge.net/codenarc-rules-basic.html
http://codenarc.sourceforge.net/codenarc-rules-braces.html
http://codenarc.sourceforge.net/codenarc-rules-concurrency.html

style: enable basic, braces, and concurrency codenarc rules

---

build.gradle

https://github.com/CodeNarc/CodeNarc/blob/master/CHANGELOG.md#version-12-jul-2018

chore: update codenarc to version 1.2

---

uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/variables.less

Comments for `@color4*` and `@color5*` mention `color3`.
This is a backport/forwardport of https://github.com/Jasig/uPortal-start/pull/178

Updated comments in variables.less

---

gradle.properties

In both releases the untar, unjar and unzip will no longer extract entries whose names would make the created files be placed outside of the destination directory by default. This is based on a recommendation by the Snyk Security Research Team.
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2C …

chore: update ant to version 1.10.4

---

gradle.properties

https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111364-2018-07-10

chore: update aws sdk to version 1.11.364

---

gradle.properties

chore: update aws sdk to version 1.11.371

---

gradle.properties

https://ant.apache.org/antnews.html

chore: update ant to version 1.10.5

---

package-lock.json
package.json

https://eslint.org/blog/2018/07/eslint-v5.1.0-released
https://eslint.org/blog/2018/07/eslint-v5.2.0-released

chore: update eslint to version 5.2.0

---

uPortal-webapp/package-lock.json
uPortal-webapp/package.json

https://github.com/less/less.js/blob/master/CHANGELOG.md#371

chore: update less to version 3.7.1

---

uPortal-webapp/src/main/resources/layout/theme/respondr/respondr.xsl

Adding a css class for guest page, to be able to customize the skin depending on authenticated or not authenticated, without need to deploy a new skin only for this need.
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resource …

feat(respondr): Adding class guest to body for css

---

uportal-war/src/main/java/org/jasig/portal/layout/dao/jpa/StylesheetUserPreferencesImpl.java
uportal-war/src/main/resources/properties/db/tables.xml

Checklist
[ x] the [individual contributor license agreement][] is signed
Description of change
Adds indexes to SS_USER_PREF_ID and USER_NAME

Added indexes for up_user and ss_user UP-4.3

---

uPortal-content/uPortal-content-portlet/src/main/java/org/apereo/portal/portlet/dao/jpa/PortletPreferenceImpl.java

fix(#1217): Change name from 100,000 length clob to 4,000 varchar.

---

uPortal-security/uPortal-security-core/src/main/java/org/apereo/portal/security/oauth/IdTokenFactory.java

Provide all user attributes defined in org.apereo.portal.security.oauth.IdTokenFactory.customClaims as multivalued.
[WCAG 2.0 AA]: …

fix(oidc-token): provide customclaims as multivalued attributes

---

gradle.properties

https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111375-2018-07-26

chore: update aws sdk to version 1.11.375

---

uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/SmartLdapGroupStore.java
uPortal-webapp/src/main/resources/org/apereo/portal/groups/smartldap/init.crn
uPortal-webapp/src/main/resources/properties/contexts/groupsContext.xml

This permit to set a new king of ldap groups loading.
Docs + test will follow in some month but I can provide a description in conversation.
This code works for us and somes other since several years in production. …

UP-4711: smartLdapGroupStore improvements

---

gradle.properties
uPortal-webapp/build.gradle
uPortal-webapp/src/main/webapp/media/skins/respondr/common/common_skin.xml

Include a web component polyfill for all uPortal.
Avoids embedding a 100kb polyfill in every component on the page.

feat: add web component polyfill to uPortal

---

uPortal-webapp/src/main/resources/layout/structure/columns/columns.xsl

This pull request is intended to supersede #1284.
It contains all the commits from that one, plus an update to a comment.

Do not display the mezzanine region in focused (MAXIMIZED) mode

---

README.md
docs/README.md
gradle.properties

rel-5-2-patches has been branched to support patches to the 5.2.x line.

chore: prepare 5.3.0 snapshot

---

gradle.properties

chore: update aws sdk java version to 1.11.383

---

gradle.properties

https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111390-2018-08-17

chore: aws java sdk version 1.11.390

---

uPortal-groups/uPortal-groups-pags/src/main/java/org/apereo/portal/groups/pags/testers/ValueMissingTester.java

-   [ ] the [individual contributor license agreement][] is signed

Fixing Issue-1261 for uPortal

---

uPortal-api/uPortal-api-internal/src/main/java/org/apereo/portal/portlets/swapper/AttributeSwapperHelperImpl.java
uPortal-concurrency/src/main/java/org/apereo/portal/concurrency/IEntityCachingService.java
uPortal-persondir/src/main/java/org/apereo/portal/persondir/support/PersonManagerCurrentUserProvider.java
uPortal-rendering/src/main/java/org/apereo/portal/portlet/container/services/CachedPasswordUserInfoService.java
uPortal-rendering/src/main/java/org/apereo/portal/portlet/container/services/PersonDirectoryUserInfoService.java
uPortal-rendering/src/main/java/org/apereo/portal/portlet/session/PortletSessionExpirationManager.java
uPortal-rendering/src/main/java/org/apereo/portal/rendering/RequestRenderingPipelineUtils.java
uPortal-security/uPortal-security-authn/src/main/java/org/apereo/portal/portlet/container/services/CasTicketUserInfoService.java
uPortal-security/uPortal-security-services/src/main/java/org/apereo/portal/services/Authentication.java
uPortal-spring/src/main/java/org/apereo/portal/spring/web/context/support/PortalSessionScope.java
uPortal-utils/uPortal-utils-core/src/main/java/org/apereo/portal/concurrency/caching/AbstractEntityCachingService.java
uPortal-utils/uPortal-utils-core/src/main/java/org/apereo/portal/concurrency/caching/CacheFactoryEntityCachingService.java
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/regions.less

Revert "chore:  remove some unused/unreachable code identified by Idea 'Unuse…"

---

uPortal-groups/uPortal-groups-pags/src/main/java/org/apereo/portal/groups/pags/dao/EntityPersonAttributesGroupStore.java
uPortal-groups/uPortal-groups-pags/src/main/java/org/apereo/portal/groups/pags/testers/MissingAttributeTester.java
uPortal-groups/uPortal-groups-pags/src/test/java/org/apereo/portal/groups/pags/MultivaluedPAGSTest.java

Providing a pags tester to test if a user has an attribute.
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cf …

feat: Adding Missing User Attribute pags

---

gradle.properties

chore: update webcomponents polyfill to version 2.1.3

---

gradle.properties

https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111414-2018-09-21

chore: update aws sdk java to version 1.11.414

---

gradle.properties

https://github.com/xmlunit/xmlunit/blob/master/RELEASE_NOTES.md#xmlunit-for-java-262---released-2018-08-27

chore: update xmlunit to version 2.6.2

---

build.gradle

chore: update nebula gradle lint to version 10.1.0

---

build.gradle

https://github.com/CodeNarc/CodeNarc/blob/master/CHANGELOG.md#version-121-aug-2018

chore: update codenarc to version 1.2.1

---

build.gradle

https://github.com/nebula-plugins/gradle-lint-plugin/releases/tag/v10.1.2

chore: update gradle lint to version 10.1.2

---

gradle.properties

chore: aws sdk java 1.11.421

---

gradle.properties

https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111423-2018-10-05

chore: update aws sdk java to version 1.11.423

---

uPortal-webapp/src/main/webapp/WEB-INF/jsp/Invoker/login.jsp

Removed stray curly brace from login.jsp

fix: Removed stray curly brace from login.jsp

---

gradle.properties
uPortal-webapp/build.gradle
uPortal-webapp/src/main/webapp/WEB-INF/jsp/Invoker/sitemap.jsp
uPortal-webapp/src/main/webapp/WEB-INF/jsp/Search/searchRest.jsp
uPortal-webapp/src/main/webapp/media/skins/respondr/common/common_skin.xml

removes old promise polyfill, which has been superceded by core-js.
removes old template polyfill, which has been superceded by webcomponentjs.

refactor: include whatwg fetch polyfill

---

uPortal-portlets/src/main/java/org/apereo/portal/portlets/search/google/GoogleCustomSearchService.java
uPortal-webapp/src/main/resources/properties/contexts/servicesContext.xml
uPortal-webapp/src/test/java/org/apereo/portal/portlets/search/google/GoogleCustomSearchServiceTest.java
uPortal-webapp/src/test/resources/org/apereo/portal/portlets/search/google/result.json

Update Google Custom Search class to support changes in remote service.

1325 google custom search

---

docs/COMMITTERS.md

Welcome @jonathanmtran, @jgribonvald, and @mairi! :wave:

docs: add new committers

---

gradle.properties

chore: update aws sdk java to version 1.11.440

---

README.md
docs/README.md

Only show build status for latest uPortal 5 release and for 4.3 patches

docs: clean badges

---

docs/implement/analytics/tincan.md

Updated version of <https://apereo.atlassian.net/wiki/spaces/UPM41/pages/103942294/TinCan+API+Configuration+4.2+>

docs: add guide for tincan analytics

---

docs/developer/soffits/securing_apis.md

Minor syntax fix in the developer documentation for Soffits.
Fixes #1450 

fix(1450): Remove invalid semi-colon in soffit docs

---

gradle.properties

Chore: update webjar dependencies

---

README.md
docs/README.md

docs: remove issue stats, site has been replaced with an unrelated blog

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

https://blog.github.com/changelog/2018-12-05-issue-template-automation-improvements

docs: automatically add appropriate tag/label to issues created with template

---

.github/SUPPORT.md

Jira has been replaced with GitHub issues

docs: update reference from Jira to GitHub issues

---

uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/ChildKeyAsCnModifier.java
uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/IChildKeyModifier.java
uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/LdapRecord.java
uPortal-groups/uPortal-groups-smartldap/src/main/java/org/apereo/portal/groups/smartldap/SmartLdapGroupStore.java
uPortal-webapp/src/main/resources/org/apereo/portal/groups/smartldap/init.crn

Address small bugs in SmartLDAP code, add recursive getParents() method, and make child key modification optional.
Resolves #1384.

fix(1384): SmartLDAP fixes and improvements

---

uPortal-webapp/src/main/java/org/apereo/portal/context/rendering/RenderingPipelineConfiguration.java
uPortal-webapp/src/main/resources/layout/theme/respondr/respondr.xsl

This PR is a reboot of #1462.
@jgribonvald -- does this change work?

feat: extract favicon path as property to be able to customize it without modifying it into the xsl

---

gradle.properties

https://blog.getbootstrap.com/2018/12/13/bootstrap-3-4-0/

chore: upgrade twitter bootstrap to version 3.4.0

---

uPortal-webapp/src/main/webapp/WEB-INF/jsp/BackgroundPreference/viewBackgroundPreference.jsp
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/header.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/navigation.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/no-chrome.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/portlet.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/regions.less

These change follow issue #1448 
The first commit it sure but the second should be tested on different browsers (I need help for that).
[WCAG 2.0 AA]: …

Fix: on z-index

---

gradle.properties

chore: update core js bundle to beta 8

---

docs/fr/HISTORIQUE.md
docs/fr/README.md

docs: improve French doc

---

package-lock.json
package.json

updates lodash to version 4.17.11

chore: update package lock file to pin newer version of lodash

---

gradle.properties

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.15.1
https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1

chore: update webjars

---

build.gradle

chore: update gradle lint to verison 10.4.2

---

README.md

docs: update links to previous versions of the uPortal manual

---

build.gradle

chore: update codenarc

---

build.gradle

chore: update gradle lint

---

uPortal-security/uPortal-security-authn/src/main/java/org/apereo/portal/security/provider/SimpleSecurityContext.java

Resolves #1760
-   [x] the [individual contributor license agreement](https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement) is signed
-   [x] commit message follows [commit guidelines](https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit)
Adds a simple warning log when someone tries to use the local login.

feat(local login): Add a warning to the logs when an attempt to use local login occurs

---

docs/COMMITTERS.md

Welcome to the committer team @cbeach47!

docs: add Chris Beach as a committer

---

docs/COMMITTERS.md

Welcome to the committer team @rmathis!

docs: add Ryan Mathis as a committer

---

docs/developer/other/RELEASE.md

Doc (release): update the notes on the release process

---

uPortal-security/uPortal-security-mvc/build.gradle
uPortal-security/uPortal-security-mvc/src/main/java/org/apereo/portal/url/ClassicMaxInactiveStrategy.java
uPortal-security/uPortal-security-mvc/src/main/java/org/apereo/portal/url/IMaxInactiveStrategy.java
uPortal-security/uPortal-security-mvc/src/main/java/org/apereo/portal/url/MaxInactiveFilter.java
uPortal-security/uPortal-security-mvc/src/main/java/org/apereo/portal/url/RequireValidSessionFilter.java
uPortal-security/uPortal-security-mvc/src/test/java/org/apereo/portal/url/ClassicMaxInactiveStrategyTest.java
uPortal-security/uPortal-security-mvc/src/test/java/org/apereo/portal/url/MaxInactiveFilterTest.java
uPortal-webapp/src/main/resources/properties/contexts/mvcContext.xml
uPortal-webapp/src/main/resources/properties/contexts/servlet/jsonRenderingServletContext.xml
uPortal-webapp/src/main/resources/properties/contexts/servlet/renderingServletContext.xml
uPortal-webapp/src/main/webapp/WEB-INF/web.xml

fix(maxInactive): Refactor MaxInactiveInterceptor to MaxInactiveFilter

---

uPortal-webapp/src/main/resources/properties/contexts/securityContext.xml

See https://groups.google.com/a/apereo.org/d/msg/uportal-user/44Uw1YP8_Mg/hLaTlEVZFAAJ

fix: updated encodeServiceUrl of the ticketValidationFilter bean to true

---

uPortal-webapp/src/main/webapp/WEB-INF/jsp/ImportExportPortlet/import.jsp

fix: prevent upload form from refreshing page

---

uPortal-webapp/src/main/webapp/media/skins/common/javascript/uportal/up-tab-manager.js

fix: add targetTab var to up-tab-manager.js

---

uPortal-webapp/src/main/resources/properties/portal.properties

This change documents the property that needs to be set in order to disable search indexing. See https://groups.google.com/a/apereo.org/forum/#!topic/uportal-dev/4FQrfqPAMP8

docs: added documentation regarding org.apereo.portal.index.relativePath

---

build.gradle

https://github.com/CodeNarc/CodeNarc/blob/master/CHANGELOG.md#version-15----nov-2019
[WCAG 2.0 AA]: …

chore: update codenarc to version 1.5

---

package-lock.json
package.json
uPortal-webapp/src/main/webapp/media/skins/respondr/common/common.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/content.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/entity-selector.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/gallery.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/grids.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/header.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/jsr-168.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/mixins.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/navigation.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/no-chrome.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/personalization.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/portlet-manager.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/portlet.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/rating.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/regions.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/search.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/tabs.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/tags.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/variables.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/views/activity.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/views/googleAnalytics.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/views/sitemap.less

Same lint and style as before, using the official plugins which work with much newer versions of eslint and stylelint.
[WCAG 2.0 AA]: …

style: use official eslint and stylelint prettier plugins

---

package-lock.json
uPortal-webapp/package-lock.json

chore: update package lockfiles

---

uPortal-webapp/src/main/resources/properties/contexts/portletContainerContext.xml
uPortal-webapp/src/main/resources/properties/contexts/schedulerContext.xml

chore: add queue size vars to portletThreadPool and uPortalTaskExecutor

---

uPortal-webapp/src/main/webapp/WEB-INF/jsp/Marketplace/portlet/view.jsp

Fixes:
- filter by category now works
- The interaction between the `A-Z Index`, `Category`, and the keyword search, and promoting the concept that you can't combine a keyword filter and a category filter.
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smi …

bugfix: portlet marketplace UX tweaks

---

uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/rest/ImportExportController.java

Importing a group data file via Import/Export Admin portlet fails.
The issue was that the import controller loads the main tag, `<group>`, and uses that to find an importer. The actual importer is keyed on `group-membership` so fails. The key is used in a few places, like creating the export filename, so this controller key change limits the rippled effect of updating all the import/export code. …

fix: handle group-membership imports

---

uPortal-portlets/build.gradle

fix: add missing jackson joda datatype jar for stats portlet

---

.github/workflows/CI.yml
uPortal-webapp/src/main/resources/properties/contexts/securityContext.xml

should fix the long time issue with Cas Proxy conf #1374 
Thanks to @markmclaren to looked on this long issue and providing the tips !
[WCAG 2.0 AA]: …

fix: Cas proxy configuration from Spring Bean management

---

uPortal-webapp/src/main/resources/org/apereo/portal/portlets/NewsReaderPortlet/NewsReader.cpd.xml
uPortal-webapp/src/main/resources/properties/i18n/Messages.properties

fix: add missing feedView preference to RSS portlet options

---

README.md
build.gradle
docs/HISTORY.md
docs/README.md
docs/building-and-deploying-uportal.md
docs/fr/HISTORIQUE.md
docs/fr/README.md
docs/fr/implementer/user-attributes/README.md
docs/fr/monter-et-deployer-uportal.md
docs/implement/layout-management/make-a-fragment.md
docs/implement/user-attributes/README.md
gradle.properties
uPortal-portlets/src/main/java/org/apereo/portal/portlets/portletadmin/PortletDefinitionFormValidator.java
uPortal-security/uPortal-security-core/src/main/java/org/apereo/portal/security/firewall/README.md
uPortal-security/uPortal-security-core/src/main/java/org/apereo/portal/security/firewall/RequestParameterPolicyEnforcementFilter.java

-   [X] documentation is changed or added
Move old doc links to new Repository links.

doc: fix new repo links

---

uPortal-api/uPortal-api-internal/src/main/java/org/apereo/portal/portlets/favorites/FavoritesUtils.java
uPortal-api/uPortal-api-internal/src/test/java/org/apereo/portal/portlets/favorites/FavoritesUtilsTest.java
uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/layout/dlm/remoting/UpdatePreferencesServlet.java
uPortal-api/uPortal-api-rest/src/test/java/org/apereo/portal/layout/dlm/remoting/UpdatePreferencesServletTest.java
uPortal-portlets/src/main/java/org/apereo/portal/portlets/favorites/FavoritesController.java

Fix: uniqueness on favorited portlets GH:2275

---

uPortal-groups/uPortal-groups-core/src/main/java/org/apereo/portal/groups/ReferenceIndividualGroupService.java

fix: handle null return from iterator

---

uPortal-content/uPortal-content-portlet/src/main/java/org/apereo/portal/portlet/dao/jpa/PortletLocalizationData.java

Somehow tablename has been incorrect for sometime. 

fix: correct tablename in PortletLocalizationData.java

---

uPortal-content/uPortal-content-portlet/src/main/java/org/apereo/portal/portlet/dao/jpa/PortletEntityImpl.java

Adding cache to portlet entity states collection

fix: add cache to portlet window state collection

---

uPortal-web/src/main/java/org/apereo/portal/portlet/rendering/PortletExecutionManager.java

History in #2283 .
Personalization is now applied to Portlet chrome titles.

Apply personalization on portlet chrome title

---

uPortal-health/src/main/java/org/apereo/portal/health/DatabaseHealthChecker.java
uPortal-health/src/main/java/org/apereo/portal/health/HealthCheckController.java
uPortal-health/src/main/java/org/apereo/portal/health/IHealthChecker.java
uPortal-health/src/main/java/org/apereo/portal/health/MemoryHealthChecker.java

feat: add memory and db query info to health-check

---

uPortal-api/uPortal-api-rest/src/main/java/org/apereo/portal/utils/web/PersonalizationFilter.java

Adding a couple NPE checks - no functional change to the personalization flow.

#2443 add NPE checks

---

docs/implement/user-attributes/README.md
uPortal-web/src/main/java/org/apereo/portal/portlet/rendering/PortletExecutionManager.java

History in #2477 .
Personalizes the 'content' of a portlet render.

Personalize portlet body content

---

docs/COMMITTERS.md

doc: add Laura McCord to committer's doc

---

docs/developer/other/RELEASE.md

Added pre-release notice and review dependencies sections to RELEASE.md.

docs: add pre-release notice and review deps sections to RELEASE.md

---

uPortal-events/src/main/java/org/apereo/portal/events/analytics/AnalyticsPortalEventsController.java
uPortal-webapp/src/main/webapp/media/skins/respondr/common/common_skin.xml
uPortal-webapp/src/main/webapp/scripts/portal-analytics.js

* feat: initial structure of portal analytics
* WIP - addEventListeners on the page seem to work with web components
* WIP - cleaned up unneeded code
* Updates from PR review
* feat: portal analytics - tie in UX to API
* feat: portal-analytics: formatting
* feat: portal-analytics: format js …

Feat/portal analytics frontend (#2588)

---

.github/workflows/CI.yml

More context at: https://github.com/gradle/wrapper-validation-action#readme
This checks that the binary jar file is a trusted version provided by the gradle team
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/propert …

ci: check that gradle wrapper is valid as part of testing flow

---

.github/PULL_REQUEST_TEMPLATE.md
docs/CHANGES.md
uPortal-webapp/src/main/resources/properties/portal.properties

doc: create init CHANGES.md

---

docs/COMMITTERS.md

doc: update inactive committers

---

docs/CHANGES.md
uPortal-webapp/src/main/resources/properties/ehcache-no-jgroups.xml

-   [x] any changes that impact configuration or the database DDL added to `CHANGES.md`
Caches added to ehcache.xml were not added to ehcache-no-jgroups.xml and CHANGES.md

config: add caches to ehcache-no-jgroups.xml and to CHANGES.md

---

uPortal-core/src/test/java/org/apereo/portal/FunctionalNameTypeTest.java
uPortal-url/src/test/java/org/apereo/portal/url/ParameterMapTest.java
uPortal-web/src/test/java/org/apereo/portal/portlet/container/services/PortletCookieServiceImplTest.java

-   [ ] new security keys and comments added to `security.properties`
-   [ ] new general keys and comments added to `portal.properties`
-   [x] any changes that impact configuration or the database DDL added to `CHANGES.md`
Aim is to increase the test coverage, line coverage and branch coverage of the modules I have implemented the unit tests for. …

unit test implemented

---

.github/workflows/CI.yml

alternative to https://github.com/uPortal-Project/uPortal/pull/2723
This uses a T shaped build matrix to cover a large number of configurations.
* On Linux it tests multiple Java versions and distributions.
* Across MacOS and Windows, it tests Java 11 on the adopt-jdk distribution.
Before there were 18 jobs (3 Operating Systems * 3 Java distributions * 2 Java versions).
With this change there are 8 jobs (3 Java distributions * 2 Java versions + 2 Operating Systems). …

ci: simplify cross platform testing, option 1

---

build.gradle

Update configuration to allow latest plugin version.

chore: upgrade release plugin

---

gradle.properties
uPortal-rendering/src/main/java/org/apereo/portal/portlet/rendering/LazyServletOutputStream.java
uPortal-utils/uPortal-utils-core/src/main/java/org/apereo/portal/utils/DelegatingServletOutputStream.java
uPortal-utils/uPortal-utils-core/src/main/java/org/apereo/portal/utils/web/AbstractHttpServletRequestWrapper.java
uPortal-utils/uPortal-utils-core/src/main/java/org/apereo/portal/utils/web/AbstractHttpServletResponseWrapper.java

Codes changes (adding new methods) for servlet 3.1.0 compatibility.

chore: upgrade to servlet 3.1.0

---

.github/workflows/CI.yml

-   [x] new security keys and comments added to `security.properties`
-   [x] new general keys and comments added to `portal.properties`
-   [x] any changes that impact configuration or the database DDL added to `CHANGES.md`
> [!IMPORTANT]
> As of `v3` this action has been superceded by `gradle/actions/wrapper-validation`.
> Any workflow that uses `gradle/wrapper-validation-action@v3` will transparently delegate to `gradle/actions/wrapper-validation@v3`.
>
> Users are encouraged to update their …

chore: update gradle wrapper to new namespace

---

.github/workflows/CI.yml

Migrate to new actions based off https://github.com/gradle/actions/releases/tag/v4.0.0

chore(ci): setup gradle action and submit dependencies back to GitHub

---

package-lock.json
uPortal-webapp/package.json
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/content.less
uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/grids.less

Upgraded Less to v4.2.0
File changes required are fractions need to be surrounded by parentheses inside `percentage()` function.

chore: update less files for compatibility with less v4
